# Automatically generated by Pynguin.
import pysnooper.variables as module_0

def test_case_0():
    try:
        int_0 = 3522
        attrs_0 = module_0.Attrs(int_0)
    except BaseException:
        pass

def test_case_1():
    try:
        str_0 = '+VIkrN'
        exploding_0 = module_0.Exploding(str_0)
        bool_0 = None
        exploding_1 = module_0.Exploding(exploding_0, bool_0)
    except BaseException:
        pass

def test_case_2():
    try:
        str_0 = 'data_list'
        indices_0 = module_0.Indices(str_0)
        var_0 = None
        var_1 = slice(var_0)
        var_2 = indices_0[:var_1]
        var_3 = indices_0.__getitem__(str_0)
    except BaseException:
        pass