# Automatically generated by Pynguin.
import pysnooper.variables as module_0

def test_case_0():
    complex_0 = None
    var_0 = module_0.needs_parentheses(complex_0)

def test_case_1():
    str_0 = 'excluded_key'
    indices_0 = module_0.Indices(str_0, str_0)
    var_0 = slice(str_0)
    var_1 = indices_0[var_0]