# Automatically generated by Pynguin.
import youtube_dl.downloader.http as module_0

def test_case_0():
    try:
        float_0 = -415.243005
        str_0 = 'X06hKdOw'
        int_0 = 42
        http_f_d_0 = module_0.HttpFD(int_0, int_0)
        var_0 = http_f_d_0.real_download(float_0, str_0)
    except BaseException:
        pass