# Automatically generated by Pynguin.
import tornado.locks as module_0
import builtins as module_1

def test_case_0():
    try:
        condition_0 = module_0.Condition()
    except BaseException:
        pass

def test_case_1():
    try:
        event_0 = module_0.Event()
        str_0 = event_0.__repr__()
        optional_0 = None
        base_exception_0 = module_1.BaseException()
        traceback_0 = None
        releasing_context_manager_0 = module_0._ReleasingContextManager(event_0)
        lock_0 = module_0.Lock()
        lock_0.__aenter__()
        releasing_context_manager_0.__exit__(optional_0, base_exception_0, traceback_0)
    except BaseException:
        pass

def test_case_2():
    try:
        bytes_0 = b'<\xdc'
        releasing_context_manager_0 = module_0._ReleasingContextManager(bytes_0)
        event_0 = module_0.Event()
        event_0.clear()
        lock_0 = module_0.Lock()
        awaitable_0 = event_0.wait()
    except BaseException:
        pass

def test_case_3():
    try:
        lock_0 = module_0.Lock()
        float_0 = 20.0
        event_0 = module_0.Event()
        awaitable_0 = event_0.wait(float_0)
    except BaseException:
        pass

def test_case_4():
    try:
        lock_0 = module_0.Lock()
        event_0 = module_0.Event()
        event_0.set()
        str_0 = lock_0.__repr__()
        event_1 = module_0.Event()
        bool_0 = event_1.is_set()
        event_2 = module_0.Event()
        bool_1 = event_0.is_set()
        int_0 = -2232
        semaphore_0 = module_0.Semaphore(int_0)
    except BaseException:
        pass

def test_case_5():
    try:
        semaphore_0 = module_0.Semaphore()
        awaitable_0 = semaphore_0.acquire()
    except BaseException:
        pass

def test_case_6():
    try:
        int_0 = 625
        semaphore_0 = module_0.Semaphore(int_0)
        semaphore_0.__enter__()
    except BaseException:
        pass

def test_case_7():
    try:
        bounded_semaphore_0 = module_0.BoundedSemaphore()
        bounded_semaphore_0.release()
    except BaseException:
        pass

def test_case_8():
    try:
        lock_0 = module_0.Lock()
        str_0 = lock_0.__repr__()
        semaphore_0 = module_0.Semaphore()
        semaphore_0.release()
        semaphore_0.release()
        awaitable_0 = lock_0.acquire()
    except BaseException:
        pass

def test_case_9():
    try:
        lock_0 = module_0.Lock()
        lock_0.release()
    except BaseException:
        pass

def test_case_10():
    try:
        lock_0 = module_0.Lock()
        lock_0.__enter__()
    except BaseException:
        pass

def test_case_11():
    try:
        bytes_0 = b'\x84\xe8\xeb\x88\n\xcf'
        releasing_context_manager_0 = module_0._ReleasingContextManager(bytes_0)
        base_exception_0 = module_1.BaseException()
        tuple_0 = None
        lock_0 = module_0.Lock()
        lock_0.__aexit__(releasing_context_manager_0, base_exception_0, tuple_0)
        event_0 = module_0.Event()
        list_0 = [event_0]
        base_exception_1 = module_1.BaseException(*list_0)
        optional_0 = None
        lock_1 = module_0.Lock()
        lock_1.__exit__(event_0, base_exception_1, optional_0)
    except BaseException:
        pass

def test_case_12():
    try:
        semaphore_0 = module_0.Semaphore()
        bounded_semaphore_0 = module_0.BoundedSemaphore()
        base_exception_0 = module_1.BaseException()
        list_0 = [semaphore_0, semaphore_0]
        event_0 = None
        bounded_semaphore_1 = module_0.BoundedSemaphore()
        tuple_0 = (event_0, bounded_semaphore_1)
        semaphore_0.__exit__(list_0, base_exception_0, tuple_0)
    except BaseException:
        pass

def test_case_13():
    try:
        lock_0 = module_0.Lock()
        event_0 = module_0.Event()
        event_0.set()
        str_0 = event_0.__repr__()
        str_1 = lock_0.__repr__()
        str_2 = lock_0.__repr__()
        event_1 = module_0.Event()
        releasing_context_manager_0 = module_0._ReleasingContextManager(event_0)
        releasing_context_manager_0.__enter__()
        event_2 = module_0.Event()
        bool_0 = event_2.is_set()
        condition_0 = module_0.Condition()
    except BaseException:
        pass

def test_case_14():
    try:
        lock_0 = module_0.Lock()
        float_0 = 20.0
        event_0 = module_0.Event()
        event_0.set()
        event_0.set()
        str_0 = lock_0.__repr__()
        releasing_context_manager_0 = module_0._ReleasingContextManager(float_0)
        releasing_context_manager_0.__enter__()
        event_1 = module_0.Event()
        bool_0 = event_0.is_set()
        condition_0 = module_0.Condition()
    except BaseException:
        pass