# Automatically generated by Pynguin.
import tornado.locks as module_0

def test_case_0():
    event_0 = module_0.Event()

def test_case_1():
    lock_0 = module_0.Lock()

def test_case_2():
    event_0 = module_0.Event()
    bool_0 = event_0.is_set()

def test_case_3():
    float_0 = -201.922
    event_0 = module_0.Event()
    event_0.set()
    releasing_context_manager_0 = module_0._ReleasingContextManager(float_0)
    releasing_context_manager_0.__enter__()

def test_case_4():
    semaphore_0 = module_0.Semaphore()
    str_0 = semaphore_0.__repr__()

def test_case_5():
    semaphore_0 = module_0.Semaphore()
    semaphore_0.release()

def test_case_6():
    lock_0 = module_0.Lock()
    str_0 = lock_0.__repr__()

def test_case_7():
    event_0 = module_0.Event()
    event_0.set()