# Automatically generated by Pynguin.
import argparse as module_0
import httpie.client as module_1
import httpie.cli.dicts as module_2
import pathlib as module_3

def test_case_0():
    try:
        namespace_0 = module_0.Namespace()
        request_headers_dict_0 = module_1.make_default_headers(namespace_0)
    except BaseException:
        pass

def test_case_1():
    try:
        namespace_0 = module_0.Namespace()
        dict_0 = module_1.make_send_kwargs(namespace_0)
    except BaseException:
        pass

def test_case_2():
    try:
        namespace_0 = module_0.Namespace()
        dict_0 = module_1.make_send_kwargs_mergeable_from_env(namespace_0)
    except BaseException:
        pass

def test_case_3():
    try:
        namespace_0 = module_0.Namespace()
        request_headers_dict_0 = module_2.RequestHeadersDict()
        request_headers_dict_1 = module_1.finalize_headers(request_headers_dict_0)
        dict_0 = module_1.make_request_kwargs(namespace_0, request_headers_dict_1)
    except BaseException:
        pass

def test_case_4():
    try:
        dict_0 = {}
        request_headers_dict_0 = module_2.RequestHeadersDict(**dict_0)
        request_headers_dict_1 = module_1.finalize_headers(request_headers_dict_0)
        namespace_0 = module_0.Namespace()
        namespace_1 = None
        str_0 = '\n        Override username/password serialization to allow unicode.\n\n        See https://github.com/httpie/httpie/issues/212\n\n        '
        str_1 = "'1LscC-fb5&;8"
        path_0 = module_3.Path()
        iterable_0 = module_1.collect_messages(namespace_1, path_0)
        str_2 = module_1.ensure_path_as_is(str_0, str_1)
        path_1 = module_3.Path()
        request_headers_dict_2 = module_1.make_default_headers(namespace_0)
    except BaseException:
        pass

def test_case_5():
    try:
        bool_0 = None
        str_0 = '_npElE&+5'
        session_0 = module_1.build_requests_session(bool_0, str_0)
    except BaseException:
        pass

def test_case_6():
    try:
        bool_0 = True
        session_0 = module_1.build_requests_session(bool_0)
        namespace_0 = module_0.Namespace()
        path_0 = None
        bytes_0 = b'\xbf\xe6\x07_\xb9\x02\xc4xv\xf1\xaf'
        iterable_0 = module_1.collect_messages(namespace_0, path_0, bytes_0)
        str_0 = '$0$j/wzh5'
        str_1 = 'gq\tlvyDYefimQ=+GdKzl'
        bool_1 = True
        dict_0 = {str_0: str_0, str_1: bool_1, str_0: iterable_0}
        request_headers_dict_0 = module_2.RequestHeadersDict(iterable_0, **dict_0)
    except BaseException:
        pass