# Automatically generated by Pynguin.
import httpie.client as module_0
import httpie.cli.dicts as module_1

def test_case_0():
    pass

def test_case_1():
    bool_0 = False
    session_0 = module_0.build_requests_session(bool_0)

def test_case_2():
    int_0 = -1043
    dict_0 = {int_0: int_0}
    var_0 = module_0.dump_request(dict_0)

def test_case_3():
    request_headers_dict_0 = module_1.RequestHeadersDict()
    request_headers_dict_1 = module_0.finalize_headers(request_headers_dict_0)

def test_case_4():
    str_0 = 'Content-Type'
    str_1 = 'User-Agent'
    str_2 = 'Accept'
    str_3 = ' application/json '
    str_4 = ' HTTPie '
    var_0 = None
    var_1 = {str_0: str_3, str_1: str_4, str_2: var_0}
    request_headers_dict_0 = module_1.RequestHeadersDict(var_1)
    bytes_0 = b'application/json'
    bytes_1 = b'HTTPie'
    bytes_2 = {str_0: bytes_0, str_1: bytes_1}
    request_headers_dict_1 = module_1.RequestHeadersDict(bytes_2)
    request_headers_dict_2 = module_0.finalize_headers(request_headers_dict_0)
    request_headers_dict_3 = module_1.RequestHeadersDict()
    request_headers_dict_4 = module_0.finalize_headers(request_headers_dict_2)
    str_5 = '   '
    str_6 = {str_0: str_5, str_1: str_4}
    request_headers_dict_5 = module_1.RequestHeadersDict(str_6)