# Automatically generated by Pynguin.
import pymonet.maybe as module_0
import builtins as module_1

def test_case_0():
    try:
        callable_0 = None
        dict_0 = {}
        list_0 = [dict_0, dict_0]
        bool_0 = False
        str_0 = 'inf'
        bool_1 = False
        maybe_0 = module_0.Maybe(str_0, bool_1)
        maybe_1 = module_0.Maybe(maybe_0, bool_1)
        var_0 = maybe_1.to_try()
        maybe_2 = module_0.Maybe(list_0, bool_0)
        var_1 = maybe_2.map(callable_0)
    except BaseException:
        pass

def test_case_1():
    try:
        bytes_0 = b'\xbd*R\xbf\xc1\x19;g\xcf6'
        list_0 = [bytes_0, bytes_0]
        bool_0 = True
        maybe_0 = module_0.Maybe(bool_0, bool_0)
        var_0 = maybe_0.to_validation()
        callable_0 = None
        var_1 = maybe_0.map(callable_0)
        object_0 = module_1.object(*list_0)
    except BaseException:
        pass

def test_case_2():
    try:
        tuple_0 = None
        object_0 = module_1.object()
        list_0 = [tuple_0, tuple_0]
        bool_0 = False
        var_0 = None
        int_0 = 148
        maybe_0 = module_0.Maybe(int_0, bool_0)
        var_1 = maybe_0.get_or_else(var_0)
        maybe_1 = module_0.Maybe(list_0, bool_0)
        var_2 = maybe_1.bind(object_0)
    except BaseException:
        pass

def test_case_3():
    try:
        str_0 = '\n=N."!uX$u`?4=W'
        var_0 = None
        bool_0 = False
        maybe_0 = module_0.Maybe(var_0, bool_0)
        maybe_1 = module_0.Maybe(var_0, bool_0)
        bool_1 = True
        maybe_2 = module_0.Maybe(var_0, bool_1)
        maybe_3 = module_0.Maybe(var_0, bool_1)
        list_0 = [str_0, maybe_2]
        var_1 = maybe_2.ap(bool_0)
        bool_2 = True
        maybe_4 = module_0.Maybe(var_0, bool_2)
        maybe_5 = module_0.Maybe(var_0, bool_1)
        var_2 = maybe_2.to_lazy()
        maybe_6 = module_0.Maybe(list_0, bool_1)
        callable_0 = None
        var_3 = maybe_5.filter(callable_0)
        var_4 = maybe_6.to_box()
        var_5 = maybe_6.to_try()
        maybe_7 = module_0.Maybe(var_0, bool_0)
        float_0 = 3067.3
        var_6 = maybe_1.ap(float_0)
    except BaseException:
        pass

def test_case_4():
    try:
        list_0 = []
        object_0 = module_1.object(*list_0)
        bool_0 = False
        str_0 = 'Jg\\v8*husp\x0b\x0bx3np Jpw'
        str_1 = '\n    First is a Monoid that will always return the first, value when 2 First instances are combined.\n    '
        maybe_0 = module_0.Maybe(str_1, bool_0)
        var_0 = maybe_0.filter(str_0)
    except BaseException:
        pass