# Automatically generated by Pynguin.
import pymonet.maybe as module_0
import builtins as module_1

def test_case_0():
    pass

def test_case_1():
    bool_0 = True
    maybe_0 = module_0.Maybe(bool_0, bool_0)
    var_0 = maybe_0.to_either()

def test_case_2():
    object_0 = module_1.object()
    bool_0 = False
    maybe_0 = module_0.Maybe(bool_0, bool_0)
    bool_1 = maybe_0.__eq__(object_0)

def test_case_3():
    object_0 = module_1.object()
    bool_0 = True
    maybe_0 = module_0.Maybe(bool_0, bool_0)
    bool_1 = maybe_0.__eq__(object_0)

def test_case_4():
    float_0 = None
    set_0 = set()
    bool_0 = True
    maybe_0 = module_0.Maybe(set_0, bool_0)
    var_0 = maybe_0.ap(float_0)

def test_case_5():
    int_0 = -82
    callable_0 = None
    str_0 = 'WlCt m\x0cV\\Hd,'
    bool_0 = True
    maybe_0 = module_0.Maybe(str_0, bool_0)
    var_0 = maybe_0.map(callable_0)
    bool_1 = True
    var_1 = maybe_0.to_lazy()
    maybe_1 = module_0.Maybe(int_0, bool_1)
    dict_0 = None
    object_0 = module_1.object()
    float_0 = -451.55791
    var_2 = None
    var_3 = maybe_0.get_or_else(var_2)
    var_4 = maybe_0.bind(float_0)
    bytes_0 = b'\xd4\xd2'
    tuple_0 = (dict_0, object_0, maybe_1, bytes_0)
    var_5 = maybe_0.filter(tuple_0)
    var_6 = maybe_1.to_lazy()
    var_7 = maybe_1.to_box()
    var_8 = maybe_0.to_box()

def test_case_6():
    callable_0 = None
    float_0 = -1364.779673
    bool_0 = True
    maybe_0 = module_0.Maybe(float_0, bool_0)
    var_0 = maybe_0.filter(callable_0)

def test_case_7():
    var_0 = None
    dict_0 = {}
    bool_0 = False
    maybe_0 = module_0.Maybe(dict_0, bool_0)
    var_1 = maybe_0.get_or_else(var_0)

def test_case_8():
    var_0 = None
    dict_0 = {}
    bool_0 = True
    maybe_0 = module_0.Maybe(dict_0, bool_0)
    var_1 = maybe_0.get_or_else(var_0)

def test_case_9():
    str_0 = 'gHi2o*fga'
    bool_0 = False
    maybe_0 = module_0.Maybe(str_0, bool_0)
    var_0 = maybe_0.to_either()

def test_case_10():
    str_0 = 'gHi2o*fga'
    bool_0 = False
    maybe_0 = module_0.Maybe(str_0, bool_0)
    var_0 = maybe_0.to_either()
    bool_1 = False
    object_0 = module_1.object()
    tuple_0 = (bool_1, object_0)
    maybe_1 = module_0.Maybe(tuple_0, bool_1)
    bool_2 = maybe_1.__eq__(object_0)
    var_1 = maybe_1.to_box()

def test_case_11():
    object_0 = module_1.object()
    int_0 = 2199
    bool_0 = True
    maybe_0 = module_0.Maybe(int_0, bool_0)
    bool_1 = maybe_0.__eq__(object_0)
    dict_0 = {}
    bool_2 = True
    maybe_1 = module_0.Maybe(dict_0, bool_2)
    var_0 = maybe_1.to_box()

def test_case_12():
    list_0 = []
    bool_0 = True
    maybe_0 = module_0.Maybe(list_0, bool_0)
    var_0 = maybe_0.to_try()
    float_0 = -462.0064
    bool_1 = False
    maybe_1 = module_0.Maybe(float_0, bool_1)
    var_1 = maybe_1.to_lazy()
    var_2 = maybe_1.to_try()

def test_case_13():
    int_0 = 1828
    bool_0 = True
    maybe_0 = module_0.Maybe(int_0, bool_0)
    var_0 = maybe_0.to_lazy()

def test_case_14():
    float_0 = -2607.366423
    str_0 = 'wDB=cctw8k\\a'
    bool_0 = True
    maybe_0 = module_0.Maybe(str_0, bool_0)
    var_0 = maybe_0.ap(float_0)
    list_0 = [var_0]
    bool_1 = False
    maybe_1 = module_0.Maybe(list_0, bool_1)
    var_1 = maybe_1.to_try()

def test_case_15():
    bytes_0 = b'\xf5\\}\xdcL\xceh\r\xce\xe3Z'
    object_0 = module_1.object()
    bool_0 = True
    set_0 = {bytes_0, bytes_0, bytes_0}
    maybe_0 = module_0.Maybe(set_0, bool_0)
    bool_1 = maybe_0.__eq__(object_0)
    list_0 = [bool_1, bytes_0, object_0]
    bool_2 = True
    maybe_1 = module_0.Maybe(list_0, bool_2)
    var_0 = maybe_1.to_try()
    var_1 = None
    maybe_2 = module_0.Maybe(var_1, bool_1)
    var_2 = maybe_2.to_validation()

def test_case_16():
    tuple_0 = ()
    list_0 = [tuple_0]
    str_0 = '8?'
    str_1 = '\n    Return increased by 1 argument.\n\n    :param value:\n    :type value: Int\n    :returns:\n    :rtype: Int\n    '
    dict_0 = {str_0: tuple_0, str_0: str_0, str_1: tuple_0, str_1: str_0}
    bool_0 = True
    maybe_0 = module_0.Maybe(dict_0, bool_0)
    var_0 = maybe_0.get_or_else(list_0)
    tuple_1 = (tuple_0,)
    bool_1 = True
    maybe_1 = module_0.Maybe(tuple_1, bool_1)
    var_1 = maybe_1.to_validation()