# Automatically generated by Pynguin.
import cookiecutter.prompt as module_0

def test_case_0():
    try:
        dict_0 = {}
        str_0 = '7z@=)#-;j6'
        var_0 = module_0.render_variable(dict_0, dict_0, str_0)
        int_0 = 758
        set_0 = None
        var_1 = module_0.read_user_variable(int_0, set_0)
    except BaseException:
        pass

def test_case_1():
    try:
        bool_0 = True
        dict_0 = {}
        str_0 = '7z@=)#-;j6'
        var_0 = module_0.render_variable(dict_0, dict_0, str_0)
        bytes_0 = b'\x93iY\xe6\xdf\xc7\x85\x8b\xfd\xa7'
        var_1 = module_0.read_user_yes_no(bool_0, bytes_0)
    except BaseException:
        pass

def test_case_2():
    try:
        str_0 = '=pb"du\\/!RsQ0'
        var_0 = module_0.read_repo_password(str_0)
    except BaseException:
        pass

def test_case_3():
    try:
        dict_0 = {}
        int_0 = 0
        var_0 = module_0.read_user_choice(dict_0, int_0)
    except BaseException:
        pass

def test_case_4():
    try:
        int_0 = -209
        var_0 = module_0.process_json(int_0)
    except BaseException:
        pass

def test_case_5():
    try:
        set_0 = set()
        var_0 = module_0.read_user_dict(set_0, set_0)
    except BaseException:
        pass

def test_case_6():
    try:
        float_0 = -3444.45402
        bytes_0 = b'0%/g<\xa9\\0'
        str_0 = ';kq\\6a'
        bytes_1 = b'n}Yf7_\x1b\xf2p\x9eD\xa3\x92\r\xf1\xcc'
        dict_0 = None
        var_0 = module_0.prompt_choice_for_config(float_0, bytes_0, str_0, bytes_1, dict_0)
    except BaseException:
        pass

def test_case_7():
    try:
        int_0 = -178
        str_0 = None
        float_0 = -1730.7
        str_1 = "sUo2+pJU'`c8\rm"
        dict_0 = {str_0: float_0, str_1: str_0, str_0: int_0}
        list_0 = [dict_0, str_1, float_0]
        dict_1 = {}
        var_0 = module_0.render_variable(int_0, list_0, dict_1)
    except BaseException:
        pass

def test_case_8():
    try:
        float_0 = 1269.0
        str_0 = ''
        str_1 = '\nIrIbfY* /P'
        tuple_0 = ()
        str_2 = '%%kyXZQs&XKZ\ti58|Z'
        set_0 = {str_1, str_2, str_1, str_1}
        var_0 = module_0.prompt_choice_for_config(float_0, str_0, str_1, tuple_0, set_0)
    except BaseException:
        pass

def test_case_9():
    try:
        float_0 = -2259.75
        var_0 = module_0.prompt_for_config(float_0)
    except BaseException:
        pass

def test_case_10():
    try:
        str_0 = '>)Ao;a5W/I'
        set_0 = {str_0, str_0, str_0}
        dict_0 = None
        list_0 = [str_0]
        float_0 = 713.91
        var_0 = module_0.prompt_choice_for_config(set_0, dict_0, set_0, list_0, float_0)
    except BaseException:
        pass

def test_case_11():
    try:
        bytes_0 = b'tyQ\xb0[\xa8\xac\xb492fZQ'
        tuple_0 = (bytes_0,)
        list_0 = []
        str_0 = ']kF'
        var_0 = module_0.render_variable(tuple_0, list_0, str_0)
        bool_0 = False
        list_1 = [bool_0, bool_0]
        list_2 = [bool_0, bool_0, bool_0]
        var_1 = module_0.read_user_dict(list_1, list_2)
    except BaseException:
        pass

def test_case_12():
    try:
        bytes_0 = b'\x93iY\xe6\xdf\xc7\x85\x8b\xfd\xa7'
        tuple_0 = None
        str_0 = '~/.cookiecutterrc'
        list_0 = [tuple_0, bytes_0, str_0]
        var_0 = module_0.read_user_choice(tuple_0, list_0)
    except BaseException:
        pass

def test_case_13():
    try:
        int_0 = -3657
        set_0 = {int_0, int_0, int_0}
        list_0 = []
        var_0 = module_0.read_user_choice(set_0, list_0)
    except BaseException:
        pass

def test_case_14():
    try:
        str_0 = 'zUC)K\tAj#tP<_!.'
        dict_0 = {}
        var_0 = module_0.read_user_dict(str_0, dict_0)
    except BaseException:
        pass

def test_case_15():
    try:
        float_0 = -2577.645
        list_0 = None
        set_0 = None
        tuple_0 = ()
        var_0 = module_0.prompt_choice_for_config(float_0, list_0, set_0, tuple_0, tuple_0)
    except BaseException:
        pass

def test_case_16():
    try:
        str_0 = '{"key": "value"}'
        var_0 = module_0.process_json(str_0)
        str_1 = '{"key1": "value1", "key2": "value2"}'
        var_1 = module_0.process_json(str_1)
        str_2 = '["value1", "value2"]'
        var_2 = module_0.process_json(str_2)
    except BaseException:
        pass