# Automatically generated by Pynguin.
import codetiming._timers as module_0

def test_case_0():
    timers_0 = module_0.Timers()

def test_case_1():
    timers_0 = module_0.Timers()
    str_0 = 'tent_timHr'
    float_0 = 1.2
    timers_0.add(str_0, float_0)
    float_1 = timers_0.median(str_0)

def test_case_2():
    timers_0 = module_0.Timers()
    str_0 = 'tent_timHr'
    float_0 = 1.2
    timers_0.add(str_0, float_0)
    timers_0.add(str_0, float_0)
    float_1 = timers_0.min(str_0)

def test_case_3():
    dict_0 = {}
    timers_0 = module_0.Timers(**dict_0)
    str_0 = 'n{SfTPP}'
    float_0 = -884.5
    timers_0.add(str_0, float_0)
    float_1 = timers_0.stdev(str_0)

def test_case_4():
    timers_0 = module_0.Timers()
    str_0 = 'test'
    float_0 = 3.5
    timers_0.add(str_0, float_0)
    float_1 = timers_0.max(str_0)

def test_case_5():
    dict_0 = {}
    timers_0 = module_0.Timers(**dict_0)
    str_0 = None
    float_0 = -1415.7
    timers_0.add(str_0, float_0)
    float_1 = timers_0.median(str_0)
    timers_0.add(str_0, float_0)
    float_2 = timers_0.stdev(str_0)
    float_3 = timers_0.total(str_0)

def test_case_6():
    timers_0 = module_0.Timers()
    str_0 = 'test_timer'
    float_0 = 4.0
    timers_0.add(str_0, float_0)
    timers_0.add(str_0, float_0)
    float_1 = timers_0.mean(str_0)