# Automatically generated by Pynguin.
import codetiming._timers as module_0

def test_case_0():
    try:
        dict_0 = {}
        timers_0 = module_0.Timers(**dict_0)
        timers_0.clear()
        str_0 = 'P&r\x0c'
        float_0 = timers_0.mean(str_0)
    except BaseException:
        pass

def test_case_1():
    try:
        str_0 = 'eD8yl4J{7{Y~:^9k8\x0b{Z'
        float_0 = 1454.03039
        timers_0 = module_0.Timers()
        timers_0.__setitem__(str_0, float_0)
    except BaseException:
        pass

def test_case_2():
    try:
        str_0 = None
        timers_0 = module_0.Timers()
        float_0 = timers_0.max(str_0)
    except BaseException:
        pass

def test_case_3():
    try:
        dict_0 = {}
        timers_0 = module_0.Timers(**dict_0)
        str_0 = 'n{SfTPP}'
        float_0 = -884.5
        timers_0.add(str_0, float_0)
        float_1 = timers_0.stdev(str_0)
        timers_1 = module_0.Timers()
        float_2 = timers_1.total(str_0)
    except BaseException:
        pass

def test_case_4():
    try:
        timers_0 = module_0.Timers()
        str_0 = '.zWhV\n%C'
        float_0 = timers_0.mean(str_0)
    except BaseException:
        pass

def test_case_5():
    try:
        str_0 = 'n",GVb_1TCY<\x0c)oPl\r$'
        list_0 = None
        list_1 = [list_0]
        timers_0 = module_0.Timers(*list_1)
        float_0 = timers_0.median(str_0)
    except BaseException:
        pass

def test_case_6():
    try:
        str_0 = " does not support item assignment. Use '.add()' to update values."
        timers_0 = module_0.Timers()
        float_0 = timers_0.stdev(str_0)
    except BaseException:
        pass

def test_case_7():
    try:
        str_0 = " does not support item assignment. Use '.add()' to update values."
        timers_0 = module_0.Timers()
        timers_1 = module_0.Timers()
        float_0 = timers_1.count(str_0)
    except BaseException:
        pass