# Automatically generated by Pynguin.
import dataclasses_json.mm as module_0
import builtins as module_1

def test_case_0():
    try:
        schema_f_0 = module_0.SchemaF()
    except BaseException:
        pass

def test_case_1():
    try:
        tuple_0 = ()
        str_0 = 'xtKiDg(@8:%'
        mapping_0 = None
        timestamp_field_0 = module_0._TimestampField(load_default=mapping_0, data_key=str_0)
        bytes_0 = b'w\x7fp\x96Y\xba28\x1b\xc4'
        type_0 = None
        dict_0 = None
        iso_field_0 = module_0._IsoField(load_default=tuple_0, data_key=str_0, attribute=str_0)
        union_field_0 = module_0._UnionField(tuple_0, type_0, dict_0)
        var_0 = module_0.build_type(iso_field_0, type_0, bytes_0, bytes_0, union_field_0)
    except BaseException:
        pass

def test_case_2():
    try:
        str_0 = 'SQm*1c@MSq0[}b\x0bzZ}b{'
        bytes_0 = b'U\xac\xc2<t\x7fRz\xe8'
        float_0 = -1153.232
        var_0 = module_0.build_type(str_0, bytes_0, float_0, str_0, float_0)
    except BaseException:
        pass

def test_case_3():
    try:
        str_0 = 'yM\na\\Duz2 &^wB'
        dict_0 = {str_0: str_0, str_0: str_0, str_0: str_0, str_0: str_0}
        list_0 = [str_0]
        bytearray_0 = module_1.bytearray()
        str_1 = '=X?{'
        dict_1 = {str_0: dict_0, str_1: str_0}
        list_1 = [dict_1, dict_1, dict_1]
        var_0 = None
        list_2 = [bytearray_0, list_1, var_0]
        bytes_0 = b'\xe3\n0f\x9bx\xca\x8d\x94 \xae\xe4-\xf6S\xf5\x87\xf3\xc3'
        tuple_0 = (list_0, list_2, bytes_0)
        set_0 = {var_0}
        timestamp_field_0 = module_0._TimestampField(dump_default=dict_1, attribute=str_0, allow_none=set_0)
        type_0 = module_0.build_schema(dict_0, tuple_0, timestamp_field_0, bytes_0)
    except BaseException:
        pass

def test_case_4():
    try:
        bytes_0 = b'\x92\xc9\x86S\xad\xb5\xc0\xba4\xd1\xf8\x91\xa2R'
        set_0 = set()
        var_0 = module_0.schema(bytes_0, bytes_0, set_0)
    except BaseException:
        pass