# Automatically generated by Pynguin.
import pymonet.task as module_0

def test_case_0():
    pass

def test_case_1():
    str_0 = '\n        If Maybe is empty return default_value, in other case.\n\n        :param default_value: value to return if Maybe is empty\n        :type default_value: Any\n        :returns: value of Maybe or default_value\n        :rtype: A\n        '
    task_0 = module_0.Task(str_0)

def test_case_2():
    dict_0 = {}
    int_0 = -1045
    task_0 = module_0.Task(int_0)
    var_0 = task_0.map(dict_0)

def test_case_3():
    dict_0 = None
    list_0 = [dict_0, dict_0, dict_0]
    list_1 = []
    task_0 = module_0.Task(list_1)
    var_0 = task_0.bind(list_0)
    task_1 = module_0.Task(dict_0)