# Automatically generated by Pynguin.
import pysnooper.pycompat as module_0
import datetime as module_1

def test_case_0():
    try:
        int_0 = -450
        var_0 = module_0.timedelta_parse(int_0)
    except BaseException:
        pass

def test_case_1():
    try:
        float_0 = 3744.0
        var_0 = module_0.timedelta_format(float_0)
    except BaseException:
        pass

def test_case_2():
    try:
        str_0 = '1:00:00:00'
        var_0 = module_0.timedelta_parse(str_0)
        int_0 = 1
        timedelta_0 = module_1.timedelta()
        timedelta_1 = module_1.timedelta()
        str_1 = '0:00:00:00.123456'
        var_1 = module_0.timedelta_parse(str_1)
    except BaseException:
        pass