# Automatically generated by Pynguin.
import pysnooper.utils as module_0

def test_case_0():
    try:
        list_0 = []
        set_0 = set()
        float_0 = 176.288553
        var_0 = module_0.get_shortish_repr(list_0, set_0, float_0)
        str_0 = 'test'
        bool_0 = True
        list_1 = [bool_0, str_0, str_0, str_0]
        var_1 = module_0.get_shortish_repr(bool_0, list_1)
    except BaseException:
        pass

def test_case_1():
    try:
        str_0 = 'S\n8'
        dict_0 = {str_0: str_0, str_0: str_0, str_0: str_0}
        list_0 = [dict_0]
        var_0 = module_0.truncate(list_0, str_0)
    except BaseException:
        pass

def test_case_2():
    try:
        str_0 = 'q'
        str_1 = 'dKJ]p,0;w]5'
        dict_0 = {str_0: str_0, str_1: str_1}
        var_0 = module_0.ensure_tuple(dict_0)
        writable_stream_0 = module_0.WritableStream()
    except BaseException:
        pass

def test_case_3():
    try:
        list_0 = None
        list_1 = [list_0, list_0, list_0, list_0]
        var_0 = module_0.get_shortish_repr(list_0, list_1)
    except BaseException:
        pass

def test_case_4():
    try:
        float_0 = -1068.362
        list_0 = [float_0, float_0, float_0]
        str_0 = '*ARI&}pd!QwK\x0c0".j\x0bl7'
        list_1 = None
        var_0 = module_0.truncate(str_0, list_1)
        dict_0 = {str_0: float_0}
        writable_stream_0 = module_0.WritableStream(*list_0, **dict_0)
    except BaseException:
        pass

def test_case_5():
    try:
        dict_0 = {}
        bool_0 = True
        var_0 = module_0.truncate(dict_0, bool_0)
        str_0 = ",w}Gvnb  kH'{"
        var_1 = module_0.ensure_tuple(str_0)
        str_1 = 'bU'
        var_2 = module_0.shitcode(str_1)
        bool_1 = False
        var_3 = module_0.ensure_tuple(bool_1)
        str_2 = 'get_ho\t=rce'
        list_0 = [str_2, dict_0, dict_0]
        var_4 = module_0.ensure_tuple(list_0)
        str_3 = None
        var_5 = module_0.get_shortish_repr(str_3)
        list_1 = [var_2, dict_0, str_2, str_2]
        var_6 = module_0.shitcode(str_2)
        var_7 = module_0.get_shortish_repr(bool_0)
        var_8 = module_0.get_repr_function(list_1, list_1)
    except BaseException:
        pass

def test_case_6():
    try:
        dict_0 = {}
        str_0 = 'bU'
        str_1 = '+n'
        bool_0 = True
        var_0 = module_0.truncate(str_1, bool_0)
        str_2 = 'get_ho\t=rce'
        str_3 = None
        var_1 = module_0.get_shortish_repr(str_3)
        list_0 = [str_0, dict_0, str_2, str_2]
        var_2 = module_0.get_repr_function(list_0, list_0)
    except BaseException:
        pass