# Automatically generated by Pynguin.
import pysnooper.utils as module_0

def test_case_0():
    pass

def test_case_1():
    list_0 = []
    var_0 = module_0.shitcode(list_0)

def test_case_2():
    str_0 = 'CYv0@#RjJ\x0cl~0_zT3"\x0c'
    var_0 = module_0.get_shortish_repr(str_0)

def test_case_3():
    str_0 = 'Ddy<Gw@(0M%cByII\r'
    var_0 = module_0.normalize_repr(str_0)

def test_case_4():
    int_0 = -1759
    var_0 = module_0.ensure_tuple(int_0)

def test_case_5():
    str_0 = 'Heo, 世界!'
    var_0 = module_0.shitcode(str_0)
    str_1 = 'Hello, \udc80!'
    var_1 = module_0.shitcode(str_1)

def test_case_6():
    str_0 = 'hello'
    var_0 = module_0.shitcode(str_0)
    str_1 = 'hell\x00o'
    var_1 = module_0.shitcode(str_1)
    str_2 = 'hellö'
    var_2 = module_0.shitcode(str_2)
    str_3 = 'hellÿ'
    var_3 = module_0.shitcode(str_3)
    str_4 = '\x00'
    var_4 = module_0.shitcode(str_4)
    str_5 = ''
    var_5 = module_0.shitcode(str_5)
    str_6 = 'hëll'
    var_6 = module_0.shitcode(str_6)
    str_7 = 'hell\x00'
    var_7 = module_0.shitcode(str_7)
    var_8 = module_0.shitcode(str_1)
    str_8 = 'All tests passed!'
    var_9 = print(str_8)