# Automatically generated by Pynguin.
import youtube_dl.postprocessor.common as module_0

def test_case_0():
    post_processor_0 = module_0.PostProcessor()

def test_case_1():
    float_0 = 35.42
    bytes_0 = b'_\xbd]\x1b\x93;\xae'
    post_processor_0 = module_0.PostProcessor(bytes_0)
    var_0 = post_processor_0.set_downloader(float_0)

def test_case_2():
    bytes_0 = b'\x0f\x16\x1d/I\xab\xdf\x82\x05\xf6\xb4\x94\xe7,\x19(\x99\xae'
    set_0 = {bytes_0, bytes_0}
    post_processor_0 = module_0.PostProcessor()
    var_0 = post_processor_0.run(set_0)