# Automatically generated by Pynguin.
import typesystem.tokenize.tokenize_json as module_0

def test_case_0():
    str_0 = '[1, 2, 3]'
    token_0 = module_0.tokenize_json(str_0)

def test_case_1():
    str_0 = '{"key": "value"}'
    token_0 = module_0.tokenize_json(str_0)
    token_1 = module_0.tokenize_json(str_0)
    str_1 = 'true'
    token_2 = module_0.tokenize_json(str_1)
    str_2 = 'null'
    token_3 = module_0.tokenize_json(str_2)
    token_4 = module_0.tokenize_json(str_2)