# Automatically generated by Pynguin.
import typesystem.tokenize.tokenize_json as module_0
import typesystem.fields as module_1

def test_case_0():
    try:
        tokenizing_decoder_0 = module_0._TokenizingDecoder()
    except BaseException:
        pass

def test_case_1():
    try:
        bytes_0 = b'{\x04\xf8\x06]\xc5\x98\x1dcm'
        token_0 = module_0.tokenize_json(bytes_0)
    except BaseException:
        pass

def test_case_2():
    try:
        str_0 = 'OA6<XAK'
        token_0 = module_0.tokenize_json(str_0)
    except BaseException:
        pass

def test_case_3():
    try:
        bytes_0 = b'2\xfa%J\xfa'
        token_0 = module_0.tokenize_json(bytes_0)
    except BaseException:
        pass

def test_case_4():
    try:
        bytes_0 = b'{\x04\xf8\x06]\xc5\x98\x1dcm'
        bytes_1 = b'\xf5\xaf'
        bool_0 = False
        field_0 = module_1.Field(default=bytes_0, allow_null=bool_0)
        any_0 = module_0.validate_json(bytes_1, field_0)
    except BaseException:
        pass

def test_case_5():
    try:
        bytes_0 = b'{\x04\xf8\x06]\xc5\x98\x1dcm'
        field_0 = None
        any_0 = module_0.validate_json(bytes_0, field_0)
    except BaseException:
        pass

def test_case_6():
    try:
        bytes_0 = b't6\xe0\xcdJ\x93\xed"ms\xa7^\xac>\xd5U'
        token_0 = module_0.tokenize_json(bytes_0)
    except BaseException:
        pass

def test_case_7():
    try:
        str_0 = '8'
        bytes_0 = None
        any_0 = module_0.validate_json(str_0, bytes_0)
    except BaseException:
        pass

def test_case_8():
    try:
        bytes_0 = b'{'
        token_0 = module_0.tokenize_json(bytes_0)
    except BaseException:
        pass

def test_case_9():
    try:
        bytes_0 = b'f6})\xe6\xf5?\xe3\xda\xb3\xcc'
        token_0 = module_0.tokenize_json(bytes_0)
    except BaseException:
        pass

def test_case_10():
    try:
        str_0 = 'name": "John", "age": 30'
        token_0 = module_0.tokenize_json(str_0)
    except BaseException:
        pass

def test_case_11():
    try:
        str_0 = '{"name": "John", "age": 30'
        token_0 = module_0.tokenize_json(str_0)
    except BaseException:
        pass

def test_case_12():
    try:
        str_0 = '{"name": +John_, "age": 30'
        token_0 = module_0.tokenize_json(str_0)
    except BaseException:
        pass

def test_case_13():
    try:
        str_0 = '{"name":"John", "age" 30'
        token_0 = module_0.tokenize_json(str_0)
    except BaseException:
        pass

def test_case_14():
    try:
        str_0 = '{"name": "John", "age": 30}'
        str_1 = '{"name": "John", "age": 30'
        token_0 = module_0.tokenize_json(str_0)
        token_1 = module_0.tokenize_json(str_1)
    except BaseException:
        pass

def test_case_15():
    try:
        str_0 = '{"name":"John", "age" 30'
        str_1 = 'true'
        token_0 = module_0.tokenize_json(str_1)
        token_1 = module_0.tokenize_json(str_0)
    except BaseException:
        pass

def test_case_16():
    try:
        str_0 = '{"name": "John", age": 30'
        token_0 = module_0.tokenize_json(str_0)
    except BaseException:
        pass

def test_case_17():
    try:
        str_0 = '{"nae": "Jhx", "ag": '
        token_0 = module_0.tokenize_json(str_0)
    except BaseException:
        pass

def test_case_18():
    try:
        str_0 = '{"name":"John" "age": 30'
        token_0 = module_0.tokenize_json(str_0)
    except BaseException:
        pass

def test_case_19():
    try:
        str_0 = '{"nam": +John_, "age": 30'
        str_1 = 'false'
        token_0 = module_0.tokenize_json(str_1)
        var_0 = None
        any_0 = module_0.validate_json(str_0, var_0)
    except BaseException:
        pass

def test_case_20():
    try:
        str_0 = '{"name": "J\rhn","age9: 30'
        token_0 = module_0.tokenize_json(str_0)
    except BaseException:
        pass