# Automatically generated by Pynguin.
import tornado.auth as module_0

def test_case_0():
    try:
        str_0 = 'SP$.T<&s^@a rv'
        list_0 = [str_0, str_0, str_0]
        open_id_mixin_0 = module_0.OpenIdMixin()
        open_id_mixin_0.authenticate_redirect(list_0)
    except BaseException:
        pass

def test_case_1():
    try:
        str_0 = '\n~\\`:O\r%'
        google_o_auth2_mixin_0 = module_0.GoogleOAuth2Mixin()
        dict_0 = google_o_auth2_mixin_0.get_authenticated_user(str_0, str_0)
        open_id_mixin_0 = module_0.OpenIdMixin()
        async_h_t_t_p_client_0 = open_id_mixin_0.get_auth_http_client()
    except BaseException:
        pass

def test_case_2():
    try:
        dict_0 = {}
        open_id_mixin_0 = module_0.OpenIdMixin(**dict_0)
        o_auth_mixin_0 = module_0.OAuthMixin(**dict_0)
        async_h_t_t_p_client_0 = o_auth_mixin_0.get_auth_http_client()
    except BaseException:
        pass

def test_case_3():
    try:
        str_0 = '(K{]\n\tQix@`wJ'
        o_auth2_mixin_0 = module_0.OAuth2Mixin()
        o_auth2_mixin_0.authorize_redirect(str_0, str_0)
    except BaseException:
        pass

def test_case_4():
    try:
        open_id_mixin_0 = module_0.OpenIdMixin()
        open_id_mixin_0.authenticate_redirect()
    except BaseException:
        pass

def test_case_5():
    try:
        twitter_mixin_0 = module_0.TwitterMixin()
        o_auth2_mixin_0 = module_0.OAuth2Mixin()
        async_h_t_t_p_client_0 = o_auth2_mixin_0.get_auth_http_client()
    except BaseException:
        pass

def test_case_6():
    try:
        str_0 = 'x+.P54,Tit>NOSg<'
        dict_0 = {}
        o_auth2_mixin_0 = module_0.OAuth2Mixin(**dict_0)
        o_auth2_mixin_0.authorize_redirect(str_0)
    except BaseException:
        pass

def test_case_7():
    try:
        o_auth2_mixin_0 = module_0.OAuth2Mixin()
        o_auth2_mixin_0.authorize_redirect()
    except BaseException:
        pass

def test_case_8():
    try:
        str_0 = 'Expect'
        dict_0 = {}
        o_auth2_mixin_0 = module_0.OAuth2Mixin(**dict_0)
        dict_1 = {o_auth2_mixin_0: str_0, str_0: o_auth2_mixin_0}
        set_0 = {str_0, o_auth2_mixin_0, str_0, o_auth2_mixin_0}
        o_auth2_mixin_0.authorize_redirect(str_0, str_0, str_0, dict_1, set_0, str_0)
    except BaseException:
        pass