# Automatically generated by Pynguin.
import flutes.iterator as module_0

def test_case_0():
    str_0 = 'scandir'
    dict_0 = {str_0: str_0, str_0: str_0, str_0: str_0, str_0: str_0}
    list_0 = [str_0]
    var_0 = module_0.scanr(dict_0, list_0)

def test_case_1():
    iterable_0 = None
    bool_0 = None
    int_0 = -3804
    float_0 = None
    iterator_0 = module_0.take(int_0, float_0)
    set_0 = {iterator_0, int_0, bool_0, int_0}
    iterator_1 = module_0.split_by(iterable_0, bool_0, criterion=iterator_0, separator=set_0)
    sequence_0 = None
    map_list_0 = module_0.MapList(iterator_1, sequence_0)

def test_case_2():
    int_0 = 620
    list_0 = []
    iterator_0 = module_0.chunk(int_0, list_0)
    lazy_list_0 = module_0.LazyList(iterator_0)
    str_0 = 'apply'
    dict_0 = {str_0: int_0, str_0: str_0}
    map_list_0 = module_0.MapList(dict_0, lazy_list_0)
    iterator_1 = map_list_0.__iter__()
    map_list_1 = module_0.MapList(iterator_1, lazy_list_0)
    iterator_2 = map_list_0.__iter__()

def test_case_3():
    str_0 = ' SplitMby '
    lazy_list_0 = module_0.LazyList(str_0)
    var_0 = list(lazy_list_0)
    int_0 = 3
    int_1 = 0
    var_1 = lambda x: x % int_0 == int_1
    iterator_0 = module_0.split_by(int_1, criterion=var_1)

def test_case_4():
    var_0 = lambda a, b: a + b
    var_1 = lambda s, x: x + s
    str_0 = 'a'
    str_1 = 'b'
    str_2 = 'c'
    str_3 = 'd'
    str_4 = [str_0, str_1, str_2, str_3]
    var_2 = module_0.scanl(var_1, str_4)
    var_3 = list(var_2)
    var_4 = lambda x, y: x * y

def test_case_5():
    int_0 = 5
    int_1 = 14
    var_0 = range(int_1)
    int_2 = -11
    var_1 = range(int_1)
    list_0 = [int_0, var_1, int_2]
    iterator_0 = module_0.drop(int_0, list_0)
    var_2 = list(iterator_0)
    var_3 = []
    iterator_1 = module_0.take(int_0, var_3)
    var_4 = list(iterator_1)
    var_5 = range(int_1)
    var_6 = list(iterator_0)

def test_case_6():
    str_0 = ' Split by: '
    bool_0 = True
    str_1 = ' '
    iterator_0 = module_0.split_by(str_0, bool_0, separator=str_1)
    var_0 = list(iterator_0)
    int_0 = 3
    int_1 = 0
    var_1 = lambda x: x % int_0 == int_1
    var_2 = list(iterator_0)

def test_case_7():
    int_0 = 5
    int_1 = 5
    int_2 = 1
    var_0 = range(int_1)
    iterator_0 = module_0.take(int_2, var_0)
    list_0 = [int_0, var_0, int_2]
    iterator_1 = module_0.drop(int_0, list_0)
    var_1 = list(iterator_1)
    var_2 = list(iterator_0)
    var_3 = list(iterator_1)
    str_0 = 'p'
    var_4 = ValueError(str_0)

def test_case_8():
    int_0 = 5
    int_1 = 0
    list_0 = [int_0, int_1, int_1]
    iterator_0 = module_0.drop(int_0, list_0)
    var_0 = list(iterator_0)

def test_case_9():
    str_0 = '8/dL\x0buy}s'
    bool_0 = True
    str_1 = ' '
    iterator_0 = module_0.split_by(str_0, bool_0, separator=str_1)
    var_0 = list(iterator_0)
    int_0 = 31
    int_1 = 0
    var_1 = lambda x: x % int_0 == int_1
    var_2 = list(iterator_0)

def test_case_10():
    int_0 = 5
    int_1 = -4
    var_0 = lambda x: x < int_0
    var_1 = range(int_1)
    iterator_0 = module_0.drop_until(var_0, var_1)
    var_2 = list(iterator_0)

def test_case_11():
    bytes_0 = b'\xbe9&?jH\x88\xd4Z\x187'
    lazy_list_0 = module_0.LazyList(bytes_0)
    list_0 = [lazy_list_0, lazy_list_0, bytes_0]
    iterator_0 = module_0.drop_until(lazy_list_0, list_0)
    str_0 = ' Split by: '
    bool_0 = False
    str_1 = ' '
    iterator_1 = module_0.split_by(str_0, bool_0, separator=str_1)
    var_0 = list(iterator_1)
    int_0 = 10
    var_1 = lambda x: x % int_0 == int_0
    iterator_2 = module_0.split_by(int_0, criterion=var_1)
    var_2 = list(iterator_1)

def test_case_12():
    int_0 = 0
    var_0 = range(int_0)
    iterator_0 = module_0.take(int_0, var_0)
    list_0 = [int_0, var_0, int_0]
    iterator_1 = module_0.drop(int_0, list_0)
    var_1 = range(int_0)
    var_2 = list(iterator_1)
    str_0 = '`n`mshoud be no-negative'
    var_3 = ValueError(str_0)