# Automatically generated by Pynguin.
import flutes.iterator as module_0

def test_case_0():
    try:
        range_0 = module_0.Range()
    except BaseException:
        pass

def test_case_1():
    try:
        iterable_0 = None
        lazy_list_0 = module_0.LazyList(iterable_0)
    except BaseException:
        pass

def test_case_2():
    try:
        bytes_0 = b'\xe3B\xb7'
        lazy_list_0 = module_0.LazyList(bytes_0)
        var_0 = lazy_list_0.__getitem__(bytes_0)
    except BaseException:
        pass

def test_case_3():
    try:
        int_0 = -1396
        list_0 = [int_0]
        range_0 = module_0.Range(*list_0)
        iterator_0 = module_0.take(int_0, range_0)
        lazy_list_0 = module_0.LazyList(iterator_0)
        var_0 = lazy_list_0.__len__()
    except BaseException:
        pass

def test_case_4():
    try:
        bool_0 = False
        list_0 = [bool_0, bool_0]
        range_0 = module_0.Range(*list_0)
        iterator_0 = range_0.__iter__()
        lazy_list_0 = module_0.LazyList(bool_0)
    except BaseException:
        pass

def test_case_5():
    try:
        bool_0 = False
        list_0 = [bool_0, bool_0]
        range_0 = module_0.Range(*list_0)
        int_0 = range_0.__len__()
        lazy_list_0 = module_0.LazyList(bool_0)
    except BaseException:
        pass

def test_case_6():
    try:
        int_0 = 1
        int_1 = 2
        int_2 = 3
        int_3 = 4
        int_4 = [int_0, int_1, int_2, int_3]
        var_0 = lambda x: x * int_1
        map_list_0 = module_0.MapList(var_0, int_4)
        var_1 = map_list_0[int_0:int_2]
    except BaseException:
        pass

def test_case_7():
    try:
        int_0 = 177
        bytes_0 = b'\x15\xaf\xaaxr\xf5\xa9\x1d\xaa'
        iterator_0 = module_0.chunk(int_0, bytes_0)
        str_0 = 'HvDW}'
        map_list_0 = module_0.MapList(iterator_0, str_0)
        int_1 = map_list_0.__len__()
        str_1 = '['
        lazy_list_0 = module_0.LazyList(str_1)
        list_0 = []
        var_0 = lazy_list_0.__getitem__(list_0)
    except BaseException:
        pass

def test_case_8():
    try:
        str_0 = 'M-`|E$)[vp8zTM7XDJ'
        lazy_list_0 = module_0.LazyList(str_0)
        var_0 = lazy_list_0.__iter__()
        range_0 = module_0.Range()
    except BaseException:
        pass

def test_case_9():
    try:
        int_0 = 3159
        bool_0 = True
        iterator_0 = module_0.chunk(int_0, bool_0)
        lazy_list_0 = module_0.LazyList(iterator_0)
        var_0 = lazy_list_0.__iter__()
        bool_1 = True
        list_0 = [bool_1, bool_1, bool_1, bool_1]
        range_0 = module_0.Range(*list_0)
    except BaseException:
        pass

def test_case_10():
    try:
        int_0 = 258
        bytes_0 = b'\xb9}\\\x0b\xcf\xfa/\xc62D\xdf\xfc\xbaJ'
        list_0 = [int_0]
        range_0 = module_0.Range(*list_0)
        var_0 = range_0.__getitem__(bytes_0)
    except BaseException:
        pass

def test_case_11():
    try:
        int_0 = 5
        var_0 = lambda x: x > int_0
        bool_0 = False
        iterator_0 = None
        iterator_1 = module_0.drop_until(bool_0, iterator_0)
        int_1 = -21
        var_1 = range(int_1)
        iterator_2 = module_0.drop_until(var_0, var_1)
        var_2 = list(iterator_2)
        float_0 = 1459.12
        int_2 = 175
        tuple_0 = None
        sequence_0 = None
        map_list_0 = module_0.MapList(tuple_0, sequence_0)
        iterator_3 = module_0.take(int_2, map_list_0)
        iterator_4 = module_0.split_by(float_0, bool_0)
        int_3 = -54
        bytes_0 = b'\x13\x08\xca\xfd\xb7t\xa4"\xbd*\xca\x8cf.\x0b\xfb'
        bytes_1 = b'.\xc7d@\x10\xcb\x8f\x10]\x89&\x82K'
        map_list_1 = module_0.MapList(bytes_0, bytes_1)
        var_3 = map_list_1.__getitem__(int_3)
    except BaseException:
        pass

def test_case_12():
    try:
        int_0 = 7
        list_0 = [int_0, int_0, int_0]
        iterator_0 = module_0.drop(int_0, list_0)
        var_0 = list(iterator_0)
        range_0 = module_0.Range(*list_0)
        lazy_list_0 = module_0.LazyList(range_0)
        bool_0 = True
        var_1 = lazy_list_0.__getitem__(bool_0)
    except BaseException:
        pass

def test_case_13():
    try:
        dict_0 = {}
        list_0 = [dict_0]
        var_0 = module_0.scanr(dict_0, dict_0, *list_0)
        range_0 = module_0.Range(*list_0)
    except BaseException:
        pass

def test_case_14():
    try:
        dict_0 = {}
        list_0 = [dict_0, dict_0]
        var_0 = module_0.scanr(dict_0, dict_0, *list_0)
    except BaseException:
        pass

def test_case_15():
    try:
        dict_0 = {}
        list_0 = [dict_0]
        var_0 = module_0.scanr(dict_0, dict_0, *list_0)
        bool_0 = False
        list_1 = [bool_0, bool_0]
        range_0 = module_0.Range(*list_1)
        iterator_0 = range_0.__iter__()
        int_0 = -5299
        bytes_0 = b'\xd0\x88T\x91tb'
        iterator_1 = module_0.split_by(int_0, separator=bytes_0)
        map_list_0 = module_0.MapList(iterator_1, range_0)
        var_1 = map_list_0.__getitem__(bool_0)
    except BaseException:
        pass

def test_case_16():
    try:
        int_0 = 5
        var_0 = range(int_0)
        int_1 = -16
        list_0 = [int_0, var_0, int_1]
        iterator_0 = module_0.drop(int_0, list_0)
        var_1 = list(iterator_0)
        str_0 = '[O"V8hi"+Y^66'
        list_1 = [str_0, var_1]
        lazy_list_0 = module_0.LazyList(list_1)
        float_0 = -2205.70608
        int_2 = 3628
        float_1 = 4082.7353
        iterator_1 = module_0.take(int_2, float_1)
        str_1 = 'G|A6c:]?\\G4C('
        lazy_list_1 = module_0.LazyList(str_1)
        var_2 = lazy_list_1.__getitem__(float_0)
    except BaseException:
        pass

def test_case_17():
    try:
        int_0 = 5
        int_1 = 20
        list_0 = [int_0, int_1, int_1]
        iterator_0 = module_0.drop(int_0, list_0)
        var_0 = list(iterator_0)
        list_1 = [var_0]
        lazy_list_0 = module_0.LazyList(list_1)
        iterator_1 = None
        var_1 = lazy_list_0.__getitem__(iterator_1)
    except BaseException:
        pass

def test_case_18():
    try:
        int_0 = 5
        var_0 = range(int_0)
        int_1 = 0
        list_0 = [int_0, var_0, int_1]
        iterator_0 = module_0.drop(int_0, list_0)
        var_1 = list(iterator_0)
        list_1 = [var_1]
        lazy_list_0 = module_0.LazyList(list_1)
        float_0 = 1287.93039
        var_2 = lazy_list_0.__getitem__(float_0)
    except BaseException:
        pass

def test_case_19():
    try:
        bytes_0 = b'\xd2\xa3Q\xd3\xf3\xb2'
        lazy_list_0 = module_0.LazyList(bytes_0)
        bool_0 = False
        var_0 = lazy_list_0.__getitem__(bool_0)
        callable_0 = None
        sequence_0 = None
        var_1 = lazy_list_0.__iter__()
        map_list_0 = module_0.MapList(callable_0, sequence_0)
        bool_1 = False
        var_2 = lazy_list_0.__getitem__(bool_1)
        var_3 = lazy_list_0.__len__()
    except BaseException:
        pass

def test_case_20():
    try:
        int_0 = 3
        list_0 = [int_0]
        range_0 = module_0.Range(*list_0)
        int_1 = range_0.__next__()
        list_1 = []
        range_1 = module_0.Range(*list_1)
    except BaseException:
        pass

def test_case_21():
    try:
        dict_0 = {}
        list_0 = [dict_0]
        var_0 = module_0.scanr(dict_0, dict_0, *list_0)
        bool_0 = False
        list_1 = [bool_0, bool_0]
        range_0 = module_0.Range(*list_1)
        iterator_0 = range_0.__iter__()
        bytes_0 = b'\xd2\xa3Q\xd3\xf3\xb2'
        lazy_list_0 = module_0.LazyList(bytes_0)
        float_0 = -877.039
        bool_1 = False
        var_1 = lazy_list_0.__getitem__(bool_1)
        callable_0 = None
        sequence_0 = None
        map_list_0 = module_0.MapList(callable_0, sequence_0)
        map_list_1 = module_0.MapList(callable_0, sequence_0)
        iterable_0 = None
        iterator_1 = module_0.split_by(iterable_0)
        var_2 = range_0.__getitem__(float_0)
        range_1 = module_0.Range()
    except BaseException:
        pass

def test_case_22():
    try:
        int_0 = 10
        var_0 = range(int_0)
        iterator_0 = module_0.chunk(int_0, var_0)
        var_1 = list(iterator_0)
        int_1 = 2
        str_0 = 'abcdef'
        iterator_1 = module_0.chunk(int_1, str_0)
        var_2 = list(iterator_1)
        int_2 = 1
        int_3 = [int_2, int_1, int_1]
        iterator_2 = module_0.chunk(int_2, int_3)
        var_3 = list(iterator_2)
        int_4 = 0
        int_5 = [int_2, int_1, int_3]
        iterator_3 = module_0.chunk(int_4, int_5)
        var_4 = list(iterator_3)
    except BaseException:
        pass

def test_case_23():
    try:
        int_0 = 3
        int_1 = 10
        var_0 = range(int_1)
        iterator_0 = module_0.chunk(int_0, var_0)
        var_1 = list(iterator_0)
        int_2 = 2
        str_0 = 'abcdef'
        iterator_1 = module_0.chunk(int_2, str_0)
        var_2 = list(iterator_1)
        int_3 = 1
        iterator_2 = module_0.chunk(int_3, int_0)
        var_3 = list(iterator_2)
    except BaseException:
        pass

def test_case_24():
    try:
        int_0 = 5
        int_1 = -10
        var_0 = range(int_1)
        iterator_0 = module_0.take(int_1, var_0)
        list_0 = [int_0, var_0, int_1]
        iterator_1 = module_0.drop(int_0, list_0)
        var_1 = list(iterator_1)
        var_2 = []
        iterator_2 = module_0.take(int_0, var_2)
        var_3 = list(iterator_0)
    except BaseException:
        pass

def test_case_25():
    try:
        int_0 = 3
        var_0 = lambda x: x < int_0
        var_1 = range(int_0)
        iterator_0 = module_0.drop_until(var_0, var_1)
        var_2 = list(iterator_0)
    except BaseException:
        pass

def test_case_26():
    try:
        int_0 = 285
        iterator_0 = module_0.split_by(int_0, criterion=int_0)
        var_0 = list(iterator_0)
    except BaseException:
        pass

def test_case_27():
    try:
        int_0 = 10
        var_0 = range(int_0)
        int_1 = 3
        int_2 = 0
        var_1 = lambda x: x % int_1 == int_2
        iterator_0 = module_0.split_by(var_0, criterion=var_1)
        var_2 = list(iterator_0)
    except BaseException:
        pass

def test_case_28():
    try:
        int_0 = 1
        int_1 = 2
        int_2 = -13
        int_3 = 4
        int_4 = [int_0, int_1, int_2, int_3]
        var_0 = lambda x: x * int_1
        map_list_0 = module_0.MapList(var_0, int_4)
        var_1 = map_list_0[int_0:int_2]
        var_2 = map_list_0[:]
    except BaseException:
        pass

def test_case_29():
    try:
        int_0 = 5
        int_1 = 10
        var_0 = range(int_1)
        iterator_0 = module_0.take(int_0, var_0)
        var_1 = list(iterator_0)
        int_2 = 0
        var_2 = range(int_1)
        iterator_1 = module_0.take(int_2, var_2)
        var_3 = list(iterator_1)
        iterator_2 = module_0.take(int_0, int_0)
        var_4 = list(iterator_2)
    except BaseException:
        pass

def test_case_30():
    try:
        int_0 = -10
        var_0 = range(int_0)
        int_1 = 0
        var_1 = range(int_0)
        iterator_0 = module_0.take(int_1, var_1)
        list_0 = [int_1, var_1, int_1]
        iterator_1 = module_0.drop(int_0, list_0)
        var_2 = list(iterator_0)
        var_3 = []
        iterator_2 = module_0.take(int_0, var_3)
        var_4 = list(iterator_0)
        var_5 = range(int_0)
        var_6 = list(iterator_1)
    except BaseException:
        pass

def test_case_31():
    try:
        str_0 = ' SplitMby '
        lazy_list_0 = module_0.LazyList(str_0)
        var_0 = list(lazy_list_0)
        var_1 = lazy_list_0.__getitem__(str_0)
    except BaseException:
        pass

def test_case_32():
    try:
        str_0 = ' SplitMby '
        lazy_list_0 = module_0.LazyList(str_0)
        var_0 = lazy_list_0.__iter__()
        var_1 = list(var_0)
        var_2 = lazy_list_0.__getitem__(str_0)
    except BaseException:
        pass

def test_case_33():
    try:
        str_0 = ' SplitMby '
        lazy_list_0 = module_0.LazyList(str_0)
        var_0 = lazy_list_0.__iter__()
        var_1 = list(lazy_list_0)
        var_2 = lazy_list_0.__len__()
        var_3 = lazy_list_0.__getitem__(str_0)
    except BaseException:
        pass

def test_case_34():
    try:
        str_0 = ' SplitMby '
        lazy_list_0 = module_0.LazyList(str_0)
        var_0 = list(lazy_list_0)
        var_1 = lazy_list_0.__iter__()
        int_0 = -953
        iterable_0 = None
        iterator_0 = module_0.drop(int_0, iterable_0)
        var_2 = lazy_list_0.__getitem__(str_0)
    except BaseException:
        pass

def test_case_35():
    try:
        str_0 = ' SplitMby '
        iterable_0 = None
        bool_0 = True
        iterator_0 = module_0.split_by(iterable_0, bool_0)
        lazy_list_0 = module_0.LazyList(str_0)
        int_0 = -953
        iterable_1 = None
        iterator_1 = module_0.drop(int_0, iterable_1)
        int_1 = 3
        int_2 = 0
        var_0 = lambda x: x % int_1 == int_2
        var_1 = list(iterator_0)
    except BaseException:
        pass

def test_case_36():
    try:
        int_0 = 5
        var_0 = lambda x: x > int_0
        iterator_0 = None
        iterator_1 = module_0.drop(int_0, iterator_0)
        int_1 = -21
        var_1 = range(int_1)
        str_0 = 'S'
        lazy_list_0 = module_0.LazyList(str_0)
        iterator_2 = module_0.drop_until(var_0, var_1)
        var_2 = list(iterator_1)
    except BaseException:
        pass