# Automatically generated by Pynguin.
import dataclasses_json.undefined as module_0

def test_case_0():
    try:
        undefined_0 = module_0.Undefined.INCLUDE
        dict_0 = None
        catch_all_undefined_parameters_0 = module_0._CatchAllUndefinedParameters()
        dict_1 = catch_all_undefined_parameters_0.handle_from_dict(undefined_0, dict_0)
    except BaseException:
        pass

def test_case_1():
    try:
        str_0 = 'F(XG!Jta23?Zl2Gw'
        ignore_undefined_parameters_0 = module_0._IgnoreUndefinedParameters()
        float_0 = None
        catch_all_undefined_parameters_0 = module_0._CatchAllUndefinedParameters()
        callable_0 = catch_all_undefined_parameters_0.create_init(float_0)
        undefined_parameter_error_0 = module_0.UndefinedParameterError(str_0)
        int_0 = 3636
        dict_0 = {ignore_undefined_parameters_0: float_0}
        raise_undefined_parameters_0 = module_0._RaiseUndefinedParameters()
        dict_1 = raise_undefined_parameters_0.handle_from_dict(int_0, dict_0)
    except BaseException:
        pass

def test_case_2():
    try:
        bytes_0 = b'\xe71Ks'
        dict_0 = {}
        ignore_undefined_parameters_0 = module_0._IgnoreUndefinedParameters()
        dict_1 = ignore_undefined_parameters_0.handle_from_dict(bytes_0, dict_0)
    except BaseException:
        pass

def test_case_3():
    try:
        str_0 = "zq'ky>$X6Xc(]w[D"
        ignore_undefined_parameters_0 = module_0._IgnoreUndefinedParameters()
        callable_0 = ignore_undefined_parameters_0.create_init(str_0)
        list_0 = [callable_0, ignore_undefined_parameters_0]
        dict_0 = {}
        undefined_parameter_error_0 = module_0.UndefinedParameterError(list_0, list_0, **dict_0)
        str_1 = '-\r:m\no'
        dict_1 = {str_1: str_1}
        catch_all_undefined_parameters_0 = module_0._CatchAllUndefinedParameters(**dict_1)
    except BaseException:
        pass

def test_case_4():
    try:
        str_0 = 'F(XG!Jta23?Zl2Gw'
        ignore_undefined_parameters_0 = module_0._IgnoreUndefinedParameters()
        float_0 = None
        catch_all_undefined_parameters_0 = module_0._CatchAllUndefinedParameters()
        callable_0 = catch_all_undefined_parameters_0.create_init(float_0)
        undefined_parameter_error_0 = module_0.UndefinedParameterError(str_0)
        dict_0 = {}
        dict_1 = catch_all_undefined_parameters_0.handle_to_dict(catch_all_undefined_parameters_0, dict_0)
    except BaseException:
        pass

def test_case_5():
    try:
        bool_0 = None
        catch_all_undefined_parameters_0 = module_0._CatchAllUndefinedParameters()
        dict_0 = catch_all_undefined_parameters_0.handle_dump(bool_0)
    except BaseException:
        pass

def test_case_6():
    try:
        str_0 = 'F(XG!Jta23?Zl2Gw'
        ignore_undefined_parameters_0 = module_0._IgnoreUndefinedParameters()
        float_0 = None
        catch_all_undefined_parameters_0 = module_0._CatchAllUndefinedParameters()
        callable_0 = catch_all_undefined_parameters_0.create_init(float_0)
        raise_undefined_parameters_0 = module_0._RaiseUndefinedParameters()
        undefined_parameter_error_0 = module_0.UndefinedParameterError(str_0)
        dict_0 = {ignore_undefined_parameters_0: float_0}
        list_0 = [callable_0, callable_0, float_0]
        dict_1 = {}
        dict_2 = ignore_undefined_parameters_0.handle_to_dict(callable_0, dict_1)
        dict_3 = catch_all_undefined_parameters_0.handle_from_dict(list_0, dict_0)
    except BaseException:
        pass