# Automatically generated by Pynguin.
import flutils.decorators as module_0

def test_case_0():
    pass

def test_case_1():
    str_0 = "Ensure the given ``path`` does **NOT** exist.\n\n    *New in version 0.4.*\n\n    If the given ``path`` does exist, it will be deleted.\n\n    If the given ``path`` is a directory, this function will\n    recursively delete all of the directory's contents.\n\n    This function processes the given ``path`` with\n    :obj:`~flutils.normalize_path`.\n\n    Args:\n        path (:obj:`str`, :obj:`bytes` or :obj:`Path <pathlib.Path>`):\n            The path to remove.\n\n    :rtype: :obj:`None`\n\n    Example:\n        >>> from flutils.pathutils import path_absent\n        >>> path_absent('~/tmp/test_path')\n\n    "
    cached_property_0 = module_0.cached_property(str_0)

def test_case_2():
    str_0 = '|c=Y^zd4<0q<2\tD\t:ooD'
    cached_property_0 = None
    dict_0 = {cached_property_0: cached_property_0, cached_property_0: cached_property_0, cached_property_0: str_0}
    int_0 = -4018
    cached_property_1 = module_0.cached_property(int_0)
    var_0 = cached_property_1.__get__(cached_property_0, dict_0)
    cached_property_2 = module_0.cached_property(str_0)