# Automatically generated by Pynguin.
import pypara.accounting.journaling as module_0

def test_case_0():
    try:
        account_0 = None
        date_0 = None
        str_0 = 'GBP'
        var_0 = None
        journal_entry_0 = module_0.JournalEntry(date_0, str_0, var_0)
        set_0 = set()
        int_0 = 30
        bool_0 = False
        tuple_0 = (set_0, int_0, bool_0)
        var_1 = journal_entry_0.post(date_0, account_0, tuple_0)
    except BaseException:
        pass