# Automatically generated by Pynguin.
import dataclasses_json.core as module_0

def test_case_0():
    try:
        extended_encoder_0 = module_0._ExtendedEncoder()
        int_0 = 238
        var_0 = extended_encoder_0.default(int_0)
    except BaseException:
        pass