# Automatically generated by Pynguin.
import dataclasses_json.core as module_0
import uuid as module_1
import decimal as module_2

def test_case_0():
    extended_encoder_0 = module_0._ExtendedEncoder()

def test_case_1():
    extended_encoder_0 = module_0._ExtendedEncoder()
    str_0 = '12345678-1234-5678-1234-567812345678'
    u_u_i_d_0 = module_1.UUID(str_0)
    var_0 = extended_encoder_0.default(u_u_i_d_0)
    var_1 = []
    var_2 = extended_encoder_0.default(var_1)
    var_3 = {}
    var_4 = extended_encoder_0.default(var_3)

def test_case_2():
    str_0 = '*"C'
    extended_encoder_0 = module_0._ExtendedEncoder()
    var_0 = extended_encoder_0.default(str_0)

def test_case_3():
    extended_encoder_0 = module_0._ExtendedEncoder()
    decimal_0 = module_2.Decimal()
    var_0 = extended_encoder_0.default(decimal_0)
    str_0 = '44|Wz~2S5#MxQe+e|n'
    str_1 = 'NcG, |1d#d'
    set_0 = {var_0, str_0, str_1}
    dict_0 = {str_0: str_0, str_1: var_0, str_1: decimal_0, str_0: set_0}
    str_2 = "': '"
    extended_encoder_1 = module_0._ExtendedEncoder(sort_keys=dict_0, indent=str_2)