# Automatically generated by Pynguin.
import blib2to3.pgen2.parse as module_0
import blib2to3.pgen2.grammar as module_1

def test_case_0():
    try:
        grammar_0 = None
        int_0 = -1771
        str_0 = '\x0bc$bj"R'
        optional_0 = None
        tuple_0 = ()
        list_0 = [tuple_0]
        tuple_1 = (int_0, str_0, optional_0, list_0)
        var_0 = module_0.lam_sub(grammar_0, tuple_1)
    except BaseException:
        pass

def test_case_1():
    try:
        int_0 = -1891
        str_0 = '_*>cYe_Vz?&QcP'
        tuple_0 = None
        grammar_0 = module_1.Grammar()
        parser_0 = module_0.Parser(grammar_0)
        bool_0 = parser_0.addtoken(int_0, str_0, tuple_0)
    except BaseException:
        pass

def test_case_2():
    try:
        grammar_0 = module_1.Grammar()
        parser_0 = module_0.Parser(grammar_0)
        parser_0.setup()
    except BaseException:
        pass

def test_case_3():
    try:
        int_0 = 3873
        dict_0 = None
        str_0 = 'Cpxv&TvJfB0z\\;],*0NH'
        int_1 = 1285
        tuple_0 = (int_1, int_0)
        tuple_1 = (str_0, tuple_0)
        grammar_0 = module_1.Grammar()
        parser_0 = module_0.Parser(grammar_0)
        parser_0.shift(int_0, dict_0, int_0, tuple_1)
    except BaseException:
        pass

def test_case_4():
    try:
        int_0 = -1130
        int_1 = -1521
        tuple_0 = (int_0, int_1)
        list_0 = [tuple_0]
        list_1 = [list_0, list_0, list_0]
        int_2 = 3503
        int_3 = -94
        dict_0 = {int_2: int_2, int_3: int_3}
        tuple_1 = (list_1, dict_0)
        int_4 = None
        tuple_2 = None
        grammar_0 = module_1.Grammar()
        parser_0 = module_0.Parser(grammar_0)
        parser_0.push(int_0, tuple_1, int_4, tuple_2)
    except BaseException:
        pass

def test_case_5():
    try:
        grammar_0 = module_1.Grammar()
        parser_0 = module_0.Parser(grammar_0)
        parser_0.pop()
    except BaseException:
        pass

def test_case_6():
    try:
        int_0 = 458
        list_0 = []
        str_0 = 'I'
        tuple_0 = (int_0, int_0)
        tuple_1 = (str_0, tuple_0)
        grammar_0 = module_1.Grammar()
        str_1 = 'f'
        parser_0 = module_0.Parser(grammar_0, str_1)
        int_1 = parser_0.classify(int_0, list_0, tuple_1)
    except BaseException:
        pass

def test_case_7():
    try:
        grammar_0 = module_1.Grammar()
        parser_0 = module_0.Parser(grammar_0)
        grammar_1 = module_1.Grammar()
        int_0 = 2479
        parser_0.setup(int_0)
    except BaseException:
        pass

def test_case_8():
    try:
        int_0 = None
        str_0 = 'D|}h59b4'
        grammar_0 = module_1.Grammar()
        optional_0 = None
        optional_1 = None
        tuple_0 = (int_0, str_0, optional_0, optional_1)
        var_0 = module_0.lam_sub(grammar_0, tuple_0)
    except BaseException:
        pass

def test_case_9():
    try:
        str_0 = 'D|}h59b4'
        int_0 = 1
        tuple_0 = (int_0, int_0)
        tuple_1 = (str_0, tuple_0)
        grammar_0 = module_1.Grammar()
        var_0 = grammar_0.copy()
        var_1 = grammar_0.copy()
        parser_0 = module_0.Parser(grammar_0, var_1)
        bool_0 = parser_0.addtoken(int_0, str_0, tuple_1)
    except BaseException:
        pass