# Automatically generated by Pynguin.
import blib2to3.pytree as module_0
import blib2to3.pgen2.grammar as module_1

def test_case_0():
    try:
        base_0 = module_0.Base()
    except BaseException:
        pass

def test_case_1():
    try:
        int_0 = 1402
        var_0 = module_0.type_repr(int_0)
    except BaseException:
        pass

def test_case_2():
    try:
        int_0 = 9
        str_0 = 'ize\t% 5t&3!jG<(*Cb{'
        leaf_0 = module_0.Leaf(int_0, str_0)
        leaf_1 = leaf_0.clone()
        int_1 = 839
        list_0 = [leaf_1]
        node_0 = module_0.Node(int_1, list_0)
        node_1 = node_0.clone()
        negated_pattern_0 = module_0.NegatedPattern(list_0)
    except BaseException:
        pass

def test_case_3():
    try:
        int_0 = 1052
        str_0 = '->'
        list_0 = [str_0, int_0, str_0, str_0]
        leaf_0 = module_0.Leaf(int_0, str_0, list_0)
    except BaseException:
        pass

def test_case_4():
    try:
        wildcard_pattern_0 = module_0.WildcardPattern()
    except BaseException:
        pass

def test_case_5():
    try:
        str_0 = ';rZfK1\r}T//pY\\&t6{fT'
        node_pattern_0 = module_0.NodePattern(str_0)
    except BaseException:
        pass

def test_case_6():
    try:
        optional_0 = None
        node_pattern_0 = module_0.NodePattern(optional_0)
    except BaseException:
        pass

def test_case_7():
    try:
        list_0 = []
        int_0 = 9
        str_0 = "%s(%s): can't parse %s"
        leaf_0 = module_0.Leaf(int_0, str_0)
        leaf_1 = leaf_0.clone()
        int_1 = 839
        list_1 = [leaf_1]
        node_0 = module_0.Node(int_1, list_1)
        node_1 = node_0.clone()
        list_2 = [leaf_0, leaf_1, leaf_1, node_1]
        iterator_0 = module_0.generate_matches(list_0, list_2)
        wildcard_pattern_0 = module_0.WildcardPattern(str_0)
        any_0 = wildcard_pattern_0.optimize()
        negated_pattern_0 = module_0.NegatedPattern()
        list_3 = [int_0, leaf_1]
        node_2 = module_0.Node(int_1, list_2, list_3)
    except BaseException:
        pass

def test_case_8():
    try:
        int_0 = 14
        list_0 = []
        node_0 = module_0.Node(int_0, list_0)
    except BaseException:
        pass

def test_case_9():
    try:
        int_0 = -583
        str_0 = 'u'
        tuple_0 = (int_0, int_0)
        tuple_1 = (str_0, tuple_0)
        list_0 = [str_0, tuple_0]
        leaf_0 = module_0.Leaf(int_0, str_0, tuple_1, str_0, list_0)
    except BaseException:
        pass

def test_case_10():
    try:
        base_pattern_0 = module_0.BasePattern()
    except BaseException:
        pass

def test_case_11():
    try:
        str_0 = "%s(%s): can't parse %s"
        int_0 = 839
        int_1 = 1517
        wildcard_pattern_0 = module_0.WildcardPattern(str_0, int_0, int_1)
        any_0 = wildcard_pattern_0.optimize()
        negated_pattern_0 = module_0.NegatedPattern()
        int_2 = None
        bool_0 = negated_pattern_0.match_seq(int_2)
    except BaseException:
        pass

def test_case_12():
    try:
        int_0 = 1
        str_0 = 'K7u (Dyq`U~;<pwz'
        wildcard_pattern_0 = module_0.WildcardPattern(str_0, int_0, int_0)
        leaf_pattern_0 = module_0.LeafPattern(int_0, str_0)
        any_0 = wildcard_pattern_0.optimize()
        leaf_0 = module_0.Leaf(int_0, str_0)
        var_0 = leaf_pattern_0.match(leaf_0, int_0)
        leaf_1 = leaf_0.clone()
        leaf_2 = leaf_1.clone()
        any_1 = wildcard_pattern_0.optimize()
        leaf_3 = leaf_2.clone()
        leaf_4 = leaf_3.clone()
        int_1 = 2973
        wildcard_pattern_1 = module_0.WildcardPattern(str_0, int_1)
        node_pattern_0 = module_0.NodePattern(int_0)
    except BaseException:
        pass

def test_case_13():
    try:
        int_0 = 9
        str_0 = "%s(%s): can't parse %s"
        leaf_0 = module_0.Leaf(int_0, str_0)
        leaf_1 = leaf_0.clone()
        leaf_2 = leaf_1.clone()
        leaf_3 = leaf_2.clone()
        int_1 = 839
        list_0 = [leaf_1]
        node_0 = module_0.Node(int_1, list_0)
        node_1 = node_0.clone()
        int_2 = -3067
        wildcard_pattern_0 = module_0.WildcardPattern(str_0, int_2)
    except BaseException:
        pass

def test_case_14():
    try:
        grammar_0 = module_1.Grammar()
        int_0 = 2053
        none_type_0 = None
        str_0 = 'Hsxo4.C15s!Nn'
        tuple_0 = (int_0, int_0)
        tuple_1 = (str_0, tuple_0)
        list_0 = []
        tuple_2 = (int_0, none_type_0, tuple_1, list_0)
        var_0 = module_0.convert(grammar_0, tuple_2)
    except BaseException:
        pass

def test_case_15():
    try:
        str_0 = 'D'
        list_0 = []
        grammar_0 = module_1.Grammar()
        int_0 = 4
        str_1 = '0x%MefO{RdIV<'
        tuple_0 = (int_0, str_1, str_0, list_0)
        var_0 = module_0.convert(grammar_0, tuple_0)
    except BaseException:
        pass

def test_case_16():
    try:
        str_0 = 'start'
        wildcard_pattern_0 = module_0.WildcardPattern(str_0)
        bool_0 = wildcard_pattern_0.match(str_0)
    except BaseException:
        pass

def test_case_17():
    try:
        int_0 = 9
        str_0 = "%s(%s): can't parse %s"
        leaf_0 = module_0.Leaf(int_0, str_0)
        leaf_1 = leaf_0.clone()
        leaf_2 = leaf_1.clone()
        leaf_3 = leaf_2.clone()
        int_1 = 839
        list_0 = [leaf_1]
        node_0 = module_0.Node(int_1, list_0)
        node_1 = node_0.clone()
        node_0.set_child(int_0, leaf_1)
    except BaseException:
        pass

def test_case_18():
    try:
        int_0 = 9
        str_0 = 'D'
        leaf_0 = module_0.Leaf(int_0, str_0)
        leaf_1 = leaf_0.clone()
        int_1 = 839
        list_0 = []
        node_0 = module_0.Node(int_1, list_0)
        node_1 = node_0.clone()
        node_2 = node_0.clone()
        str_1 = leaf_0.__repr__()
        node_0.insert_child(int_0, leaf_0)
        base_0 = module_0.Base()
    except BaseException:
        pass

def test_case_19():
    try:
        int_0 = 9
        str_0 = 'ize\t% 5t&3!jG<(*Cb{'
        leaf_0 = module_0.Leaf(int_0, str_0)
        node_pattern_0 = None
        str_1 = leaf_0.__str__()
        node_pattern_1 = module_0.NodePattern(node_pattern_0, str_0)
    except BaseException:
        pass

def test_case_20():
    try:
        grammar_0 = module_1.Grammar()
        int_0 = 298
        str_0 = '&5T%MjX-T'
        int_1 = 720
        int_2 = 7
        tuple_0 = (int_1, int_2)
        tuple_1 = (str_0, tuple_0)
        float_0 = 49.11904
        tuple_2 = (int_0, int_0, tuple_1, float_0)
        var_0 = module_0.convert(grammar_0, tuple_2)
    except BaseException:
        pass

def test_case_21():
    try:
        int_0 = 9
        str_0 = 'ize\t% 5t&3!jG<(*Cb{'
        int_1 = 839
        wildcard_pattern_0 = module_0.WildcardPattern(str_0, int_1, int_0)
    except BaseException:
        pass

def test_case_22():
    try:
        int_0 = 27
        str_0 = 'i\te%5t3!<(*C'
        wildcard_pattern_0 = module_0.WildcardPattern(str_0, int_0, int_0)
        leaf_pattern_0 = module_0.LeafPattern(int_0, str_0)
        bytes_0 = b'/\x95\x9bK\xba7\x8a\x0c\xbe\x8c\xb6V\xbb'
        bool_0 = wildcard_pattern_0.match_seq(bytes_0)
    except BaseException:
        pass

def test_case_23():
    try:
        int_0 = 1340
        str_0 = '->'
        list_0 = []
        node_0 = module_0.Node(int_0, list_0, str_0)
        str_1 = node_0.__repr__()
    except BaseException:
        pass

def test_case_24():
    try:
        list_0 = []
        int_0 = 871
        list_1 = []
        node_0 = module_0.Node(int_0, list_1)
        node_1 = node_0.clone()
        iterator_0 = module_0.generate_matches(list_0, list_1)
        leaf_pattern_0 = module_0.LeafPattern()
        iterator_1 = module_0.generate_matches(list_0, list_1)
        node_0.update_sibling_maps()
    except BaseException:
        pass

def test_case_25():
    try:
        str_0 = 'ize\t% 5t&3!jG<(*Cb{'
        int_0 = 839
        wildcard_pattern_0 = module_0.WildcardPattern(str_0, int_0, int_0)
        leaf_pattern_0 = module_0.LeafPattern(int_0, str_0)
    except BaseException:
        pass

def test_case_26():
    try:
        grammar_0 = module_1.Grammar()
        int_0 = 340
        var_0 = grammar_0.copy()
        str_0 = 'Dump of DFA for'
        tuple_0 = (int_0, int_0)
        tuple_1 = (str_0, tuple_0)
        str_1 = 'Parser driver.\n\nThis provides a high-level interface to parse a file into a syntax tree.\n\n'
        tuple_2 = (int_0, var_0, tuple_1, str_1)
        var_1 = module_0.convert(grammar_0, tuple_2)
    except BaseException:
        pass

def test_case_27():
    try:
        str_0 = 'D'
        int_0 = 839
        list_0 = []
        node_0 = module_0.Node(int_0, list_0)
        node_1 = node_0.clone()
        node_2 = node_0.clone()
        wildcard_pattern_0 = module_0.WildcardPattern(str_0)
        list_1 = []
        iterator_0 = node_1.post_order()
        list_2 = [list_1, iterator_0]
        bool_0 = wildcard_pattern_0.match_seq(list_1, list_2)
    except BaseException:
        pass

def test_case_28():
    try:
        str_0 = ''
        int_0 = 839
        list_0 = []
        node_0 = module_0.Node(int_0, list_0)
        node_1 = node_0.clone()
        node_2 = node_0.clone()
        wildcard_pattern_0 = module_0.WildcardPattern(str_0)
    except BaseException:
        pass

def test_case_29():
    try:
        int_0 = -13
        str_0 = 'ize\te% 5t&3!jG<(*Cb{'
        leaf_pattern_0 = module_0.LeafPattern(int_0, str_0)
    except BaseException:
        pass

def test_case_30():
    try:
        list_0 = []
        str_0 = '+_BpVT\n'
        int_0 = 769
        any_0 = None
        node_0 = module_0.Node(int_0, list_0, any_0, str_0)
        int_1 = -394
        var_0 = module_0.type_repr(int_1)
    except BaseException:
        pass

def test_case_31():
    try:
        int_0 = 0
        str_0 = 'i\te%5t&3!<(*C{'
        leaf_pattern_0 = module_0.LeafPattern(int_0, str_0)
        str_1 = ''
        none_type_0 = None
        leaf_0 = module_0.Leaf(int_0, str_1, none_type_0, str_0)
        var_0 = leaf_pattern_0.match(leaf_0)
        int_1 = 2914
        wildcard_pattern_0 = module_0.WildcardPattern(int_1)
    except BaseException:
        pass

def test_case_32():
    try:
        int_0 = 9
        str_0 = 'D'
        leaf_0 = module_0.Leaf(int_0, str_0)
        leaf_1 = leaf_0.clone()
        int_1 = 839
        list_0 = []
        node_0 = module_0.Node(int_1, list_0)
        node_1 = node_0.clone()
        node_2 = node_0.clone()
        str_1 = leaf_0.__repr__()
        list_1 = [leaf_0, leaf_1, leaf_1, node_2]
        wildcard_pattern_0 = module_0.WildcardPattern(str_0)
        any_0 = wildcard_pattern_0.optimize()
        str_2 = node_2.__str__()
        negated_pattern_0 = module_0.NegatedPattern(any_0)
        node_0.insert_child(int_0, leaf_0)
        negated_pattern_1 = module_0.NegatedPattern()
        int_2 = 2447
        node_0.insert_child(int_2, leaf_0)
        str_3 = "#U,'lDt}B=As^&KF"
        list_2 = [str_0, int_0, int_0]
        dict_0 = {str_2: list_1, str_3: int_1}
        base_0 = module_0.Base(*list_2, **dict_0)
    except BaseException:
        pass

def test_case_33():
    try:
        int_0 = 28
        str_0 = 'i\te%5t3!<*'
        wildcard_pattern_0 = module_0.WildcardPattern(str_0, int_0, int_0)
        leaf_pattern_0 = module_0.LeafPattern(int_0, str_0)
        bytes_0 = b''
        any_0 = wildcard_pattern_0.optimize()
        negated_pattern_0 = module_0.NegatedPattern(any_0)
        leaf_0 = module_0.Leaf(int_0, str_0)
        leaf_1 = leaf_0.clone()
        str_1 = leaf_1.__repr__()
        var_0 = leaf_pattern_0.match(leaf_1, bytes_0)
        bool_0 = wildcard_pattern_0.match_seq(int_0)
    except BaseException:
        pass

def test_case_34():
    try:
        str_0 = ')'
        int_0 = 941
        list_0 = []
        bytes_0 = b'\xec\xd5Y\x9cK\x98o,h\xdb)m\x96\x0b\x0c'
        node_0 = module_0.Node(int_0, list_0, bytes_0, str_0)
        wildcard_pattern_0 = module_0.WildcardPattern(str_0)
        int_1 = -53
        node_0.insert_child(int_1, node_0)
    except BaseException:
        pass

def test_case_35():
    try:
        int_0 = 0
        int_1 = -2721
        str_0 = '&g5\x0bepk2=:'
        leaf_0 = module_0.Leaf(int_0, str_0)
        leaf_1 = leaf_0.clone()
        leaf_2 = leaf_1.clone()
        list_0 = [leaf_2]
        int_2 = 4451
        wildcard_pattern_0 = module_0.WildcardPattern(str_0)
        any_0 = wildcard_pattern_0.optimize()
        node_0 = module_0.Node(int_2, list_0, any_0, str_0)
        iterator_0 = node_0.pre_order()
        node_1 = module_0.Node(int_1, list_0, str_0)
    except BaseException:
        pass

def test_case_36():
    try:
        str_0 = ')'
        int_0 = 941
        list_0 = []
        wildcard_pattern_0 = module_0.WildcardPattern(str_0)
        grammar_0 = module_1.Grammar()
        tuple_0 = None
        set_0 = {tuple_0, int_0, grammar_0}
        node_0 = module_0.Node(int_0, list_0, grammar_0, str_0, set_0)
    except BaseException:
        pass

def test_case_37():
    try:
        int_0 = 1
        str_0 = 'K7u (Dyq`U~;<pwz'
        wildcard_pattern_0 = module_0.WildcardPattern(str_0, int_0, int_0)
        leaf_pattern_0 = module_0.LeafPattern(int_0, str_0)
        any_0 = wildcard_pattern_0.optimize()
        base_0 = module_0.Base()
    except BaseException:
        pass