# Automatically generated by Pynguin.
import blib2to3.pytree as module_0
import blib2to3.pgen2.grammar as module_1

def test_case_0():
    int_0 = 603
    list_0 = []
    node_0 = module_0.Node(int_0, list_0)

def test_case_1():
    int_0 = 839
    list_0 = []
    node_0 = module_0.Node(int_0, list_0)
    node_1 = node_0.clone()

def test_case_2():
    int_0 = 9
    str_0 = 'ize\t% 5t&3!jG<(*Cb{'
    leaf_0 = module_0.Leaf(int_0, str_0)
    leaf_1 = leaf_0.clone()
    negated_pattern_0 = module_0.NegatedPattern()

def test_case_3():
    int_0 = 9
    str_0 = 'ize@% &3!jG<(*Cb'
    leaf_0 = module_0.Leaf(int_0, str_0)
    leaf_1 = leaf_0.clone()
    iterator_0 = leaf_0.leaves()
    leaf_pattern_0 = module_0.LeafPattern()
    str_1 = leaf_0.__repr__()
    var_0 = leaf_pattern_0.match(leaf_1)

def test_case_4():
    int_0 = 7
    str_0 = 'ize\te% 5t&3!jG<(*Cb{'
    leaf_pattern_0 = module_0.LeafPattern(int_0, str_0)

def test_case_5():
    negated_pattern_0 = module_0.NegatedPattern()
    leaf_pattern_0 = module_0.LeafPattern()

def test_case_6():
    str_0 = 'a9r$z{8<Eh|_eA?'
    wildcard_pattern_0 = module_0.WildcardPattern(str_0)

def test_case_7():
    negated_pattern_0 = module_0.NegatedPattern()

def test_case_8():
    int_0 = 7
    str_0 = 'ize\te% 5t&3!jG<(*Cb{'
    int_1 = 839
    wildcard_pattern_0 = module_0.WildcardPattern(str_0, int_0, int_0)
    leaf_pattern_0 = module_0.LeafPattern(int_0, str_0)
    iterator_0 = wildcard_pattern_0.generate_matches(leaf_pattern_0)
    negated_pattern_0 = module_0.NegatedPattern()
    bool_0 = negated_pattern_0.match(int_1)
    any_0 = wildcard_pattern_0.optimize()
    wildcard_pattern_1 = module_0.WildcardPattern(str_0)

def test_case_9():
    int_0 = 257
    int_1 = 1
    leaf_pattern_0 = module_0.LeafPattern(int_1)
    int_2 = 2
    leaf_pattern_1 = module_0.LeafPattern(int_2)
    leaf_pattern_2 = [leaf_pattern_0, leaf_pattern_1]
    str_0 = 'test_node'
    node_pattern_0 = module_0.NodePattern(int_0, leaf_pattern_2, str_0)
    var_0 = node_pattern_0.content
    var_1 = node_pattern_0.content
    var_2 = len(var_1)
    int_3 = 0
    var_3 = node_pattern_0.content[int_3]
    var_4 = node_pattern_0.content[int_1]
    str_1 = 'test_NodePattern passed!'
    var_5 = print(str_1)

def test_case_10():
    str_0 = 'X*D+$'
    wildcard_pattern_0 = module_0.WildcardPattern(str_0)
    any_0 = wildcard_pattern_0.optimize()

def test_case_11():
    int_0 = 1402
    str_0 = 'bare_name'
    wildcard_pattern_0 = module_0.WildcardPattern(str_0, int_0)
    any_0 = wildcard_pattern_0.optimize()

def test_case_12():
    str_0 = 'ize\t% 5t&3!jG<(*Cb{'
    int_0 = 863
    wildcard_pattern_0 = module_0.WildcardPattern(str_0, int_0, int_0)
    negated_pattern_0 = module_0.NegatedPattern(wildcard_pattern_0)

def test_case_13():
    list_0 = []
    int_0 = 9
    str_0 = "%s(%s): can't parse %s"
    leaf_0 = module_0.Leaf(int_0, str_0)
    leaf_1 = leaf_0.clone()
    leaf_2 = leaf_1.clone()
    leaf_3 = leaf_2.clone()
    int_1 = 839
    list_1 = [leaf_1]
    node_0 = module_0.Node(int_1, list_1)
    node_1 = node_0.clone()
    list_2 = [leaf_3, leaf_1, leaf_2, node_1]
    iterator_0 = module_0.generate_matches(list_0, list_2)
    wildcard_pattern_0 = module_0.WildcardPattern(str_0, int_0, int_0)
    node_1.append_child(leaf_0)
    wildcard_pattern_1 = module_0.WildcardPattern(str_0)

def test_case_14():
    int_0 = 9
    str_0 = 'D'
    leaf_0 = module_0.Leaf(int_0, str_0)
    leaf_1 = leaf_0.clone()
    int_1 = 839
    list_0 = []
    node_0 = module_0.Node(int_1, list_0)
    node_1 = node_0.clone()
    node_2 = node_0.clone()
    str_1 = leaf_0.__repr__()
    str_2 = node_2.__str__()
    node_0.insert_child(int_0, leaf_0)

def test_case_15():
    int_0 = 0
    str_0 = 'i\te%5t3!<(*C'
    leaf_pattern_0 = module_0.LeafPattern(int_0, str_0)
    leaf_0 = module_0.Leaf(int_0, str_0)
    leaf_1 = leaf_0.clone()
    var_0 = leaf_pattern_0.match(leaf_1)

def test_case_16():
    int_0 = 9
    str_0 = 'ize\t% 5&3!jG<(*Cb{'
    leaf_0 = module_0.Leaf(int_0, str_0)
    int_1 = 871
    list_0 = []
    node_0 = module_0.Node(int_1, list_0)
    node_1 = node_0.clone()
    leaf_pattern_0 = module_0.LeafPattern()
    var_0 = leaf_pattern_0.match(leaf_0, node_0)

def test_case_17():
    int_0 = 1
    str_0 = 'leaf_value'
    var_0 = None
    str_1 = 'prefix'
    var_1 = []
    leaf_0 = module_0.Leaf(int_0, str_0, var_0, str_1, var_1)
    iterator_0 = leaf_0.post_order()
    var_2 = next(iterator_0)

def test_case_18():
    str_0 = 'D'
    wildcard_pattern_0 = module_0.WildcardPattern(str_0)
    any_0 = wildcard_pattern_0.optimize()

def test_case_19():
    int_0 = 0
    str_0 = 'start'
    node_0 = None
    leaf_pattern_0 = module_0.LeafPattern()
    var_0 = leaf_pattern_0.match(node_0)
    wildcard_pattern_0 = module_0.WildcardPattern(str_0, int_0, int_0)
    bool_0 = wildcard_pattern_0.match(int_0)
    wildcard_pattern_1 = module_0.WildcardPattern(str_0)
    any_0 = wildcard_pattern_0.optimize()

def test_case_20():
    int_0 = 0
    str_0 = 'i\te%5t3!<(*C'
    wildcard_pattern_0 = module_0.WildcardPattern(str_0, int_0, int_0)
    leaf_pattern_0 = module_0.LeafPattern(int_0, str_0)
    bytes_0 = b''
    bool_0 = wildcard_pattern_0.match_seq(bytes_0)

def test_case_21():
    int_0 = 0
    str_0 = 'start'
    wildcard_pattern_0 = module_0.WildcardPattern(str_0, int_0, int_0)
    bool_0 = wildcard_pattern_0.match(int_0)

def test_case_22():
    int_0 = 9
    str_0 = "%s(%s): can't parse %s"
    leaf_0 = module_0.Leaf(int_0, str_0)
    leaf_1 = leaf_0.clone()
    leaf_2 = leaf_1.clone()
    list_0 = [leaf_1]
    leaf_3 = leaf_1.clone()
    grammar_0 = module_1.Grammar()
    str_1 = 'e<Pv]I ?i^?.sA5N>'
    tuple_0 = (int_0, str_0, str_1, list_0)
    var_0 = module_0.convert(grammar_0, tuple_0)
    leaf_pattern_0 = module_0.LeafPattern()
    iterator_0 = leaf_2.leaves()
    leaf_4 = leaf_2.clone()
    int_1 = 666
    negated_pattern_0 = module_0.NegatedPattern()
    list_1 = [int_0, leaf_1]
    node_0 = module_0.Node(int_1, list_0, list_1)
    negated_pattern_1 = module_0.NegatedPattern()

def test_case_23():
    int_0 = 1
    str_0 = 'test'
    leaf_0 = module_0.Leaf(int_0, str_0)
    iterator_0 = leaf_0.leaves()
    var_0 = list(iterator_0)
    var_1 = len(var_0)