# Automatically generated by Pynguin.
import cookiecutter.replay as module_0
import cookiecutter.utils as module_1

def test_case_0():
    try:
        float_0 = None
        var_0 = module_0.load(float_0, float_0)
    except BaseException:
        pass

def test_case_1():
    try:
        str_0 = 'R1Aa8~DIY3'
        complex_0 = None
        bool_0 = True
        var_0 = module_0.dump(str_0, complex_0, bool_0)
    except BaseException:
        pass

def test_case_2():
    try:
        str_0 = 'cookiecutter'
        str_1 = {str_0: str_0}
        var_0 = module_0.dump(str_0, str_0, str_1)
        var_1 = module_0.load(str_0, str_1)
    except BaseException:
        pass

def test_case_3():
    try:
        str_0 = 'Aw#'
        set_0 = set()
        var_0 = module_0.dump(str_0, str_0, set_0)
    except BaseException:
        pass

def test_case_4():
    try:
        str_0 = 'test_dir'
        str_1 = 'test_template'
        str_2 = 'key'
        str_3 = 'value'
        str_4 = {str_2: str_3}
        str_5 = {str_3: str_4}
        var_0 = module_1.make_sure_path_exists(str_0)
        var_1 = module_0.dump(str_0, str_1, str_5)
    except BaseException:
        pass

def test_case_5():
    try:
        str_0 = 'test_template'
        str_1 = 'cookiecutter'
        str_2 = 'Run hook from repo directory, clean project directory if hook fails.\n\n    :param repo_dir: Project template input directory.\n    :param hook_name: The hook to execute.\n    :param project_dir: The directory to execute the script from.\n    :param context: Cookiecutter project context.\n    :param delete_project_on_failure: Delete the project directory on hook\n        failure?\n    '
        str_3 = 'Test Project'
        str_4 = {str_2: str_3}
        str_5 = {str_1: str_4}
        var_0 = module_1.make_sure_path_exists(str_2)
        var_1 = module_0.dump(str_2, str_0, str_5)
    except BaseException:
        pass