# Automatically generated by Pynguin.
import cookiecutter.replay as module_0

def test_case_0():
    str_0 = '/path/to/replay/dir/test_template.json'
    var_0 = module_0.get_file_name(str_0, str_0)

def test_case_1():
    str_0 = 'test_template'
    str_1 = 'cookiecutter'
    var_0 = module_0.load(str_1, str_0)

def test_case_2():
    str_0 = 'test_template'
    var_0 = module_0.get_file_name(str_0, str_0)