# Automatically generated by Pynguin.
import string_utils.validation as module_0

def test_case_0():
    try:
        int_0 = 335
        int_1 = 2775
        set_0 = {int_0, int_0, int_1}
        str_0 = 'strip_html'
        bool_0 = module_0.is_slug(set_0, str_0)
        str_1 = None
        bool_1 = module_0.is_isbn(str_1)
    except BaseException:
        pass

def test_case_1():
    try:
        str_0 = "APmS}S'o&|wKd;`v5_n"
        bool_0 = module_0.is_isbn(str_0)
        bool_1 = module_0.contains_html(str_0)
        str_1 = None
        bool_2 = module_0.is_integer(str_1)
    except BaseException:
        pass

def test_case_2():
    try:
        str_0 = 'my.email@the-provider.com'
        bool_0 = module_0.is_url(str_0, str_0)
        str_1 = 'my.email@the-provider..com'
        bool_1 = module_0.is_email(str_1)
        bool_2 = module_0.is_email(str_1)
        bool_3 = module_0.is_email(str_0)
        str_2 = 'B'
        str_3 = "zO-+DlsF'"
        bool_4 = module_0.is_email(str_3)
        bool_5 = module_0.is_credit_card(str_0, str_2)
    except BaseException:
        pass

def test_case_3():
    try:
        str_0 = 'my.email@the-provider.com'
        str_1 = 'my.email@the-provider..com'
        bool_0 = module_0.is_email(str_1)
        bool_1 = module_0.is_email(str_1)
        bool_2 = module_0.is_email(str_0)
        str_2 = 'B'
        str_3 = "zO-+DlsF'"
        bool_3 = module_0.is_email(str_3)
        bool_4 = module_0.is_credit_card(str_0, str_2)
    except BaseException:
        pass

def test_case_4():
    try:
        str_0 = "\n    Checks if an object is a string.\n\n    *Example:*\n\n    >>> is_string('foo') # returns true\n    >>> is_string(b'foo') # returns false\n\n    :param obj: Object to test.\n    :return: True if string, false otherwise.\n    "
        bool_0 = True
        bool_1 = module_0.is_palindrome(str_0, bool_0)
        bool_2 = module_0.is_isbn(str_0)
        str_1 = '<uC%<9+ZNgz8\\.vn\\O\tF'
        i_s_b_n_checker_0 = module_0.__ISBNChecker(str_1)
        bool_3 = i_s_b_n_checker_0.is_isbn_10()
        bool_4 = module_0.contains_html(str_1)
        str_2 = '"\n}!@ti(nxC04Kb'
        bool_5 = module_0.is_decimal(str_0)
        bool_6 = i_s_b_n_checker_0.is_isbn_13()
        bool_7 = module_0.contains_html(str_2)
        bool_8 = module_0.is_email(str_2)
        bool_9 = module_0.is_ip(bool_3)
        bool_10 = module_0.is_credit_card(bool_4)
        str_3 = None
        bool_11 = module_0.contains_html(str_3)
    except BaseException:
        pass

def test_case_5():
    try:
        bool_0 = True
        bool_1 = False
        int_0 = 11
        dict_0 = {bool_0: bool_1, bool_1: bool_0, bool_1: bool_1, bool_1: int_0}
        bool_2 = module_0.is_uuid(dict_0)
        str_0 = 'B:`C%`\n]/R\\~'
        bool_3 = False
        int_1 = module_0.words_count(str_0)
        str_1 = '\x0b_haI\t^'
        bool_4 = module_0.is_palindrome(str_1, bool_3)
        bool_5 = module_0.is_palindrome(str_0, bool_3)
        str_2 = 'HD~kD$\nY=j3pL'
        i_s_b_n_checker_0 = module_0.__ISBNChecker(str_2)
        bool_6 = module_0.is_email(dict_0)
        bool_7 = i_s_b_n_checker_0.is_isbn_10()
        bool_8 = module_0.is_isbn_13(str_0, bool_5)
        bool_9 = i_s_b_n_checker_0.is_isbn_10()
        bool_10 = module_0.is_isbn_10(str_2)
        bool_11 = i_s_b_n_checker_0.is_isbn_13()
        bool_12 = module_0.is_ip_v6(bool_2)
        str_3 = 'e'
        bool_13 = module_0.is_isbn(str_3)
        bool_14 = module_0.is_snake_case(dict_0)
        str_4 = 'w-'
        bool_15 = module_0.is_isbn(str_4)
        str_5 = None
        int_2 = module_0.words_count(str_5)
    except BaseException:
        pass

def test_case_6():
    try:
        str_0 = '192.168.0.1'
        bool_0 = module_0.is_ip_v4(str_0)
        str_1 = '255.255.255.255'
        str_2 = '{nope}'
        bool_1 = module_0.is_json(str_2)
        str_3 = 'invalid json string'
        bool_2 = module_0.is_json(str_3)
        bool_3 = module_0.is_palindrome(str_0)
        bool_4 = False
        bool_5 = module_0.is_json(bool_4)
        bool_6 = module_0.is_json(bool_5)
        bool_7 = module_0.is_json(bool_1)
        str_4 = '{"invalid": }'
        i_s_b_n_checker_0 = module_0.__ISBNChecker(str_4)
        bool_8 = module_0.is_credit_card(str_4)
        bool_9 = module_0.is_email(str_4)
        str_5 = 'B'
        bool_10 = module_0.is_email(str_1)
        bool_11 = module_0.is_credit_card(str_1, str_5)
    except BaseException:
        pass