# Automatically generated by Pynguin.
import string_utils.validation as module_0

def test_case_0():
    str_0 = '..'
    bool_0 = module_0.is_integer(str_0)

def test_case_1():
    str_0 = "APmS}S'o&|wKd;`v5_n"
    bool_0 = module_0.is_isbn(str_0)

def test_case_2():
    str_0 = 'SPACES_INSIDE'
    str_1 = 'K8_-1.\t>;O4~}%v%+'
    bool_0 = module_0.contains_html(str_1)
    bool_1 = module_0.is_url(str_0)
    i_s_b_n_checker_0 = module_0.__ISBNChecker(str_0)
    bool_2 = i_s_b_n_checker_0.is_isbn_13()

def test_case_3():
    str_0 = '/DtA,.+gbN'
    str_1 = '\x0cyJe]|6z\\5'
    bool_0 = False
    i_s_b_n_checker_0 = module_0.__ISBNChecker(str_1, bool_0)
    bool_1 = module_0.is_isbn(str_0)
    bool_2 = module_0.is_ip_v6(i_s_b_n_checker_0)
    bool_3 = module_0.is_number(str_0)
    str_2 = 'PdT9g1&!O1I\t\teKiHq!'
    int_0 = module_0.words_count(str_2)

def test_case_4():
    dict_0 = {}
    bool_0 = module_0.is_pangram(dict_0)

def test_case_5():
    str_0 = 'b\t#'
    bool_0 = module_0.is_decimal(str_0)

def test_case_6():
    str_0 = 'm'
    bool_0 = module_0.is_url(str_0)

def test_case_7():
    str_0 = ''
    bool_0 = module_0.is_url(str_0)

def test_case_8():
    str_0 = 'my.email@the-provider.com'
    str_1 = 'my.email@the-provider..com'
    bool_0 = module_0.is_email(str_1)
    bool_1 = module_0.is_email(str_1)
    bool_2 = module_0.is_email(str_0)
    bool_3 = module_0.is_isbn_10(str_0)

def test_case_9():
    str_0 = "\\\r!1~(wS1A'"
    i_s_b_n_checker_0 = module_0.__ISBNChecker(str_0)
    bool_0 = module_0.is_json(str_0)
    bool_1 = module_0.is_email(str_0)
    i_s_b_n_checker_1 = module_0.__ISBNChecker(str_0, bool_1)
    bool_2 = i_s_b_n_checker_0.is_isbn_10()

def test_case_10():
    float_0 = -1259.81
    bool_0 = module_0.is_email(float_0)

def test_case_11():
    str_0 = 'C\'a(3"B~Gn38'
    bool_0 = module_0.is_snake_case(str_0)
    bool_1 = False
    bool_2 = module_0.is_credit_card(str_0)
    bool_3 = module_0.is_camel_case(bool_1)
    bool_4 = module_0.is_ip(bool_1)

def test_case_12():
    str_0 = '192.168.0.1'
    bool_0 = module_0.is_ip_v4(str_0)
    str_1 = 'my.email@the-provider..com'
    i_s_b_n_checker_0 = module_0.__ISBNChecker(str_1)
    bool_1 = i_s_b_n_checker_0.is_isbn_13()
    bool_2 = module_0.is_email(str_0)
    bool_3 = module_0.is_email(str_1)
    bool_4 = module_0.is_email(bool_0)
    bool_5 = module_0.is_credit_card(bool_2, str_1)

def test_case_13():
    dict_0 = {}
    bool_0 = module_0.is_camel_case(dict_0)

def test_case_14():
    bytes_0 = b'"U\xc7\x08V\x86\xe6\x04c*\x01\xb5)\x83\x0f\xa0\xa7'
    bool_0 = module_0.is_url(bytes_0)
    str_0 = 'Y$XM\x0b7h!\\"'
    bool_1 = False
    bool_2 = module_0.is_isbn(str_0, bool_1)
    str_1 = 'z, !gqLh1eE_]?<1'
    bool_3 = module_0.is_isbn_13(str_1)
    str_2 = '+'
    bytes_1 = b'u'
    bool_4 = module_0.is_snake_case(str_2, str_2)
    str_3 = 'B'
    int_0 = module_0.words_count(str_3)
    bool_5 = module_0.is_snake_case(bool_2)
    bool_6 = module_0.is_isbn_10(str_3)
    set_0 = {str_2, str_2, str_2, bytes_1}
    bool_7 = module_0.is_json(set_0)

def test_case_15():
    float_0 = 1162.025578
    bool_0 = module_0.is_pangram(float_0)
    bool_1 = True
    str_0 = 'hx3'
    bool_2 = module_0.is_number(str_0)
    bool_3 = module_0.is_json(bool_1)

def test_case_16():
    set_0 = set()
    bool_0 = module_0.is_uuid(set_0)

def test_case_17():
    bool_0 = None
    bool_1 = module_0.is_ip(bool_0)

def test_case_18():
    str_0 = 'h)r'
    i_s_b_n_checker_0 = module_0.__ISBNChecker(str_0)
    bool_0 = True
    bool_1 = i_s_b_n_checker_0.is_isbn_13()
    bool_2 = module_0.is_palindrome(str_0, bool_0)
    bool_3 = i_s_b_n_checker_0.is_isbn_10()
    bool_4 = i_s_b_n_checker_0.is_isbn_10()
    bool_5 = False
    bool_6 = module_0.is_isbn_10(str_0, bool_5)

def test_case_19():
    str_0 = '$1Uy9'
    bool_0 = module_0.is_number(str_0)
    bool_1 = False
    bool_2 = module_0.is_url(str_0)
    bool_3 = module_0.is_isbn_13(str_0, bool_1)
    dict_0 = {bool_2: bool_3}
    bool_4 = False
    bool_5 = module_0.is_palindrome(dict_0, bool_4)
    bool_6 = module_0.is_isogram(bool_3)
    bool_7 = module_0.is_isbn_13(str_0)
    bool_8 = module_0.is_ip(str_0)
    bool_9 = module_0.is_ip_v4(bool_7)

def test_case_20():
    str_0 = 'e'
    str_1 = '^\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}$'
    list_0 = [str_1]
    tuple_0 = (list_0,)
    bytes_0 = b'\xeap\xcdd\xd6n\xe6'
    bytes_1 = b''
    tuple_1 = (tuple_0, bytes_0, bytes_0, bytes_1)
    bool_0 = module_0.is_url(tuple_1)
    bool_1 = False
    bool_2 = module_0.is_palindrome(str_0, bool_1)
    bool_3 = module_0.is_number(str_0)
    bool_4 = module_0.is_uuid(str_0)
    bool_5 = module_0.is_isbn_10(str_0)
    str_2 = 'Eb<["i8'
    bool_6 = False
    str_3 = '\r!5Z/Kz'
    bool_7 = module_0.is_number(str_3)
    bool_8 = module_0.is_isbn_10(str_1)
    str_4 = ''
    i_s_b_n_checker_0 = module_0.__ISBNChecker(str_3)
    bool_9 = i_s_b_n_checker_0.is_isbn_13()
    i_s_b_n_checker_1 = module_0.__ISBNChecker(str_4)
    bool_10 = i_s_b_n_checker_1.is_isbn_10()
    bool_11 = module_0.contains_html(str_1)
    bool_12 = module_0.is_uuid(bool_3, bool_6)
    bool_13 = module_0.is_integer(str_0)
    bool_14 = module_0.is_string(str_2)
    i_s_b_n_checker_2 = module_0.__ISBNChecker(str_0, bool_14)
    bool_15 = i_s_b_n_checker_2.is_isbn_13()
    bool_16 = i_s_b_n_checker_2.is_isbn_10()
    bool_17 = i_s_b_n_checker_1.is_isbn_13()
    bool_18 = module_0.is_json(bool_5)
    bool_19 = i_s_b_n_checker_0.is_isbn_13()

def test_case_21():
    int_0 = -444
    set_0 = {int_0, int_0, int_0, int_0}
    list_0 = [set_0, set_0, int_0]
    str_0 = 'J\\QNky+?6K'
    bool_0 = module_0.is_string(str_0)
    str_1 = ''
    bool_1 = False
    i_s_b_n_checker_0 = module_0.__ISBNChecker(str_1, bool_1)
    bool_2 = i_s_b_n_checker_0.is_isbn_13()
    bool_3 = module_0.is_pangram(str_0)
    bool_4 = module_0.is_pangram(list_0)

def test_case_22():
    str_0 = 'Kn\\zt\x0b|[S|$'
    bool_0 = module_0.is_isogram(str_0)

def test_case_23():
    str_0 = 'O\r-m<gN\t$\x0cNS(\x0b'
    bool_0 = module_0.contains_html(str_0)

def test_case_24():
    str_0 = 'e{~;"e&'
    i_s_b_n_checker_0 = module_0.__ISBNChecker(str_0)
    bool_0 = i_s_b_n_checker_0.is_isbn_13()
    str_1 = 'T@*\rD'
    int_0 = module_0.words_count(str_1)

def test_case_25():
    str_0 = 'L[h'
    str_1 = ':>K/&\x0b^'
    int_0 = module_0.words_count(str_1)
    bool_0 = module_0.is_slug(str_0)
    bool_1 = module_0.is_camel_case(bool_0)
    bool_2 = module_0.is_credit_card(str_1)
    bool_3 = module_0.is_slug(str_0)
    bool_4 = module_0.is_isbn_13(str_1)

def test_case_26():
    str_0 = '.N]\rtJ\t'
    bool_0 = False
    list_0 = [str_0, str_0, bool_0, bool_0]
    bool_1 = module_0.is_full_string(list_0)
    i_s_b_n_checker_0 = module_0.__ISBNChecker(str_0, bool_0)
    bool_2 = i_s_b_n_checker_0.is_isbn_10()

def test_case_27():
    str_0 = '9780312498580'
    bool_0 = module_0.is_isbn(str_0)
    str_1 = '1506715214'
    bool_1 = module_0.is_isbn(str_1)
    str_2 = '978-0312498580'
    bool_2 = module_0.is_isbn(str_2)
    str_3 = '123456789X'
    bool_3 = module_0.is_isbn(str_3)
    str_4 = '1234567890'
    bool_4 = module_0.is_isbn(str_4)
    str_5 = '978-1234567890'
    bool_5 = module_0.is_isbn(str_5)
    bool_6 = module_0.is_isbn(str_5, bool_0)

def test_case_28():
    str_0 = ''
    i_s_b_n_checker_0 = module_0.__ISBNChecker(str_0)
    bool_0 = i_s_b_n_checker_0.is_isbn_10()
    str_1 = 'S@.0Q(21+<y'
    bool_1 = module_0.is_ip_v4(str_1)
    bool_2 = module_0.contains_html(str_1)

def test_case_29():
    str_0 = '255.200.100.75'
    bool_0 = module_0.is_ip(str_0)
    var_0 = print(bool_0)
    str_1 = '2001:db8:85a3:0000:0000:8a2e:370:7334'
    bool_1 = module_0.is_ip(str_1)
    var_1 = print(bool_1)
    str_2 = '1.2.3'
    bool_2 = module_0.is_ip(str_2)
    var_2 = print(bool_2)

def test_case_30():
    str_0 = 'm6Xq\t?R\x0c=9s)%S+CUx'
    bool_0 = module_0.is_decimal(str_0)
    str_1 = '\n    Checks if the given string contains HTML/XML tags.\n\n    By design, this function matches ANY type of tag, so don\'t expect to use it\n    as an HTML validator, its goal is to detect "malicious" or undesired tags in the text.\n\n    *Examples:*\n\n    >>> contains_html(\'my string is <strong>bold</strong>\') # returns true\n    >>> contains_html(\'my string is not bold\') # returns false\n\n    :param input_string: Text to check\n    :type input_string: str\n    :return: True if string contains html, false otherwise.\n    '
    float_0 = 83.8
    bool_1 = module_0.is_uuid(float_0)
    bool_2 = module_0.is_isogram(str_1)
    bool_3 = module_0.is_url(str_1, float_0)
    bool_4 = module_0.is_ip_v6(str_1)
    str_2 = '_uLzAuN\nUN'
    bool_5 = module_0.is_snake_case(bool_4)
    i_s_b_n_checker_0 = module_0.__ISBNChecker(str_1)
    bool_6 = i_s_b_n_checker_0.is_isbn_10()
    i_s_b_n_checker_1 = module_0.__ISBNChecker(str_1)
    bool_7 = i_s_b_n_checker_1.is_isbn_10()
    bool_8 = module_0.is_camel_case(bool_3)
    bool_9 = module_0.is_decimal(str_2)
    bool_10 = False
    bool_11 = module_0.is_camel_case(bool_2)
    bool_12 = module_0.is_palindrome(str_1, bool_10)
    str_3 = '2#i=k@\r%]N3N1p,s'
    bool_13 = module_0.contains_html(str_3)

def test_case_31():
    int_0 = 218
    bool_0 = module_0.is_isogram(int_0)

def test_case_32():
    str_0 = "\\\r!1~(wS1A'"
    i_s_b_n_checker_0 = module_0.__ISBNChecker(str_0)
    bool_0 = i_s_b_n_checker_0.is_isbn_13()
    str_1 = '"{}" must be an integer in the range 1-3999'
    bool_1 = module_0.is_json(str_1)
    bool_2 = module_0.is_email(str_1)
    i_s_b_n_checker_1 = module_0.__ISBNChecker(str_0, bool_2)
    str_2 = '@X^z>w]czrq4"D%&'
    bool_3 = module_0.is_decimal(str_2)
    str_3 = '%N+l!+_[e*{dw0'
    bool_4 = module_0.is_integer(str_3)
    bool_5 = module_0.is_camel_case(str_0)
    bool_6 = i_s_b_n_checker_0.is_isbn_13()
    str_4 = "I#|'0cr"
    bool_7 = module_0.is_decimal(str_4)
    bool_8 = i_s_b_n_checker_0.is_isbn_13()

def test_case_33():
    str_0 = 'K\tsV\\KJ/viZ1Uj=@?8ae'
    bool_0 = module_0.is_json(str_0)
    bool_1 = module_0.is_integer(str_0)
    int_0 = -1665
    bool_2 = module_0.is_isbn_10(str_0)
    bool_3 = module_0.is_pangram(int_0)
    bool_4 = module_0.is_ip_v6(bool_0)
    bool_5 = module_0.is_isogram(bool_3)
    bool_6 = True
    bool_7 = module_0.is_uuid(bool_0, bool_6)
    bytes_0 = b'D\xed'
    bool_8 = module_0.is_camel_case(bytes_0)
    bool_9 = module_0.is_ip_v4(int_0)
    bool_10 = module_0.is_camel_case(int_0)
    bool_11 = module_0.is_string(int_0)
    bool_12 = module_0.is_ip(bool_3)
    bool_13 = module_0.is_json(bool_3)
    bool_14 = module_0.is_isbn_10(str_0, bool_9)
    str_1 = 'Bs}^kG5aFn'
    int_1 = module_0.words_count(str_1)
    bool_15 = module_0.is_credit_card(bool_7)
    bool_16 = module_0.is_isogram(str_0)
    str_2 = 'w>I<<?yk<31jwug/eZ'
    bool_17 = None
    bool_18 = module_0.is_isbn_13(str_2, bool_17)
    str_3 = 'b\nc'
    bool_19 = True
    i_s_b_n_checker_0 = module_0.__ISBNChecker(str_3, bool_19)
    bool_20 = i_s_b_n_checker_0.is_isbn_13()

def test_case_34():
    str_0 = '\n    Checks if the given string contains HTML/XML tags.\n\n    By design, this function matches ANY type of tag, so don\'t expect to use it\n    as an HTML validator, its goal is to detect "malicious" or undesired tags in the text.\n\n    *Examples:*\n\n    >>> contains_html(\'my string is <strong>bold</strong>\') # returns true\n    >>> contains_html(\'my string is not bold\') # returns false\n\n    :param input_string: Text to check\n    :type input_string: str\n    :return: True if string contains html, false otherwise.\n    '
    int_0 = module_0.words_count(str_0)
    bool_0 = module_0.is_isogram(str_0)
    bool_1 = module_0.is_ip_v6(str_0)
    str_1 = 'Z@=aupsj?TO,&pD)'
    str_2 = '"\n}!@ti(nxC04Kb'
    bool_2 = module_0.is_decimal(str_2)
    bool_3 = module_0.contains_html(str_2)
    bool_4 = module_0.is_email(str_1)
    bool_5 = module_0.is_email(bool_1)
    bool_6 = module_0.is_email(str_2)
    bool_7 = module_0.is_ip_v6(str_0)
    str_3 = 'z#l'
    i_s_b_n_checker_0 = module_0.__ISBNChecker(str_3)
    bool_8 = i_s_b_n_checker_0.is_isbn_10()

def test_case_35():
    bool_0 = True
    bool_1 = module_0.is_full_string(bool_0)
    str_0 = '}V}01\x0c6)h\x0b'
    str_1 = '6'
    bool_2 = module_0.is_decimal(str_1)
    bool_3 = module_0.is_ip_v4(str_0)
    str_2 = '"QteF&W3G$'
    bool_4 = module_0.is_isbn_13(str_2)
    bool_5 = module_0.is_isbn_10(str_2, bool_0)
    bool_6 = module_0.is_ip(str_1)
    bool_7 = module_0.is_ip(str_2)
    bool_8 = False
    i_s_b_n_checker_0 = module_0.__ISBNChecker(str_0, bool_8)
    bool_9 = i_s_b_n_checker_0.is_isbn_10()
    bool_10 = i_s_b_n_checker_0.is_isbn_10()
    bool_11 = module_0.is_isbn(str_2)

def test_case_36():
    str_0 = "\n    Checks if an object is a string.\n\n    *Example:*\n\n    >>> is_string('foo') # returns true\n    >>> is_string(b'foo') # returns false\n\n    :param obj: Object to test.\n    :return: True if string, false otherwise.\n    "
    int_0 = module_0.words_count(str_0)
    str_1 = "'Y mYRouw|om"
    bool_0 = module_0.is_full_string(int_0)
    bool_1 = module_0.is_isbn_13(str_1)
    bool_2 = True
    bool_3 = module_0.is_palindrome(str_0, bool_2)
    float_0 = -348.00881
    str_2 = 'N'
    bool_4 = module_0.is_integer(str_2)
    bool_5 = False
    bool_6 = module_0.is_uuid(float_0, bool_5)
    str_3 = 'YSy2W;0Yot3'
    bool_7 = module_0.contains_html(str_3)
    bool_8 = module_0.is_decimal(str_2)
    str_4 = 'DhI:=gK~czlL\\@R\t(?_'
    bool_9 = module_0.is_email(bool_3)
    bool_10 = module_0.is_pangram(bool_1)
    bool_11 = False
    bool_12 = True
    bool_13 = module_0.is_palindrome(str_0, bool_11, bool_12)
    bool_14 = module_0.is_url(str_4)
    bool_15 = module_0.is_email(float_0)
    str_5 = '^\tG)'
    i_s_b_n_checker_0 = module_0.__ISBNChecker(str_5)
    bool_16 = i_s_b_n_checker_0.is_isbn_10()
    bool_17 = i_s_b_n_checker_0.is_isbn_10()
    bool_18 = i_s_b_n_checker_0.is_isbn_10()
    bool_19 = i_s_b_n_checker_0.is_isbn_10()

def test_case_37():
    str_0 = '8 6'
    int_0 = module_0.words_count(str_0)
    str_1 = "\n    Checks if an object is a string.\n\n    *Example:*\n\n    >>> is_string('foo') # returns true\n    >>> is_string(b'foo') # returns false\n\n    :param obj: Object to test.\n    :return: True if string, false otherwise.\n    "
    bool_0 = True
    bool_1 = module_0.is_palindrome(str_1, bool_0)
    bool_2 = module_0.is_isbn(str_1)
    str_2 = '~u<=4wo*d%\\Gk:'
    str_3 = '<uC%<9+ZNgz8\\.vn\\O\tF'
    bool_3 = module_0.is_integer(str_2)
    i_s_b_n_checker_0 = module_0.__ISBNChecker(str_2)
    bool_4 = i_s_b_n_checker_0.is_isbn_10()
    bool_5 = module_0.contains_html(str_3)
    str_4 = '"\n}!@ti(nxC04Kb'
    bool_6 = module_0.is_decimal(str_2)
    bool_7 = module_0.contains_html(str_4)
    bool_8 = module_0.is_email(str_4)
    bool_9 = module_0.is_pangram(i_s_b_n_checker_0)
    bool_10 = module_0.is_ip(bool_4)
    bool_11 = module_0.is_email(bool_7)
    i_s_b_n_checker_1 = module_0.__ISBNChecker(str_4)
    str_5 = '^\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}$'
    bool_12 = False
    i_s_b_n_checker_2 = module_0.__ISBNChecker(str_5, bool_12)
    str_6 = '489'
    bool_13 = module_0.is_integer(str_6)
    bool_14 = i_s_b_n_checker_1.is_isbn_10()

def test_case_38():
    str_0 = '192.168.0.1'
    bool_0 = module_0.is_ip_v4(str_0)
    str_1 = '{nope}'
    bool_1 = module_0.is_json(str_1)
    str_2 = 'invalid json string'
    bool_2 = module_0.is_json(str_2)
    bool_3 = module_0.is_json(bool_1)
    str_3 = '\n    Convert a snake case string into a camel case one.\n    (The original string is returned if is not a valid snake case string)\n\n    *Example:*\n\n    >>> snake_case_to_camel(\'the_snake_is_green\') # returns \'TheSnakeIsGreen\'\n\n    :param input_string: String to convert.\n    :type input_string: str\n    :param upper_case_first: True to turn the first letter into uppercase (default).\n    :type upper_case_first: bool\n    :param separator: Sign to use as separator (default to "_").\n    :type separator: str\n    :return: Converted string\n    '
    i_s_b_n_checker_0 = module_0.__ISBNChecker(str_3)
    bool_4 = i_s_b_n_checker_0.is_isbn_10()
    bool_5 = module_0.is_ip(bool_1)
    str_4 = '6R'
    str_5 = 'q\x0b3oIXU0Oi@u{'
    str_6 = "!y'UM"
    bool_6 = module_0.is_isbn(str_5)
    bool_7 = module_0.is_credit_card(bool_5, str_4)
    bool_8 = module_0.is_email(str_3)
    bool_9 = module_0.is_email(str_6)
    bool_10 = module_0.is_credit_card(str_0)

def test_case_39():
    str_0 = '192.168.0.1'
    bool_0 = module_0.is_ip_v4(str_0)
    str_1 = '255.255.255.255'
    str_2 = '{nope}'
    bool_1 = module_0.is_json(str_2)
    str_3 = 'invalid json string'
    bool_2 = module_0.is_json(str_3)
    str_4 = '{"\tey": "value", "list": [1, 2, 3]}'
    bool_3 = module_0.is_email(str_1)
    bool_4 = module_0.is_email(str_4)
    bool_5 = module_0.is_email(bool_3)
    bool_6 = module_0.is_isbn_10(str_3)

def test_case_40():
    str_0 = '192.168.0.1'
    bool_0 = module_0.is_ip_v4(str_0)
    str_1 = 'my.email@the-provider..com'
    i_s_b_n_checker_0 = module_0.__ISBNChecker(str_1)
    bool_1 = i_s_b_n_checker_0.is_isbn_13()
    bool_2 = module_0.is_email(str_0)
    bool_3 = module_0.is_email(str_1)
    bool_4 = module_0.is_email(bool_0)
    bool_5 = module_0.is_isbn_10(str_0, bool_3)

def test_case_41():
    str_0 = '192.168.0.1'
    bool_0 = module_0.is_ip_v4(str_0)
    str_1 = '255.255.255.255'
    bool_1 = module_0.is_ip_v4(str_1)
    str_2 = '256.100.50.25'
    bool_2 = module_0.is_ip_v4(str_2)
    bool_3 = module_0.is_ip_v4(str_1)
    str_3 = 'my.email@.com'
    bool_4 = module_0.is_email(str_3)
    bool_5 = module_0.is_email(bool_1)
    bool_6 = module_0.is_email(bool_1)
    bool_7 = module_0.is_email(bool_5)

def test_case_42():
    str_0 = '192.168.0.1'
    bool_0 = module_0.is_ip_v4(str_0)
    i_s_b_n_checker_0 = module_0.__ISBNChecker(str_0, bool_0)
    bool_1 = module_0.is_email(str_0)
    bool_2 = module_0.is_email(str_0)
    bool_3 = module_0.is_email(str_0)
    str_1 = 'user@domain.com/'
    str_2 = '.[(R6~(M'
    i_s_b_n_checker_1 = module_0.__ISBNChecker(str_2, bool_1)
    bool_4 = module_0.is_email(i_s_b_n_checker_1)
    bool_5 = module_0.is_email(str_1)
    bool_6 = module_0.is_email(bool_0)
    bool_7 = module_0.is_email(str_2)

def test_case_43():
    str_0 = '4539578763621486'
    str_1 = 'VISA'
    bool_0 = module_0.is_credit_card(str_0, str_1)
    str_2 = '5111111111111118'
    str_3 = 'MASTERCARD'
    bool_1 = module_0.is_credit_card(str_2, str_3)
    str_4 = '378282246310005'
    str_5 = 'AMERICAN_EXPRESS'
    bool_2 = module_0.is_credit_card(str_4, str_5)
    str_6 = '6011514433546201'
    str_7 = 'DISCOVER'
    bool_3 = module_0.is_credit_card(str_6, str_7)
    str_8 = '3530111333300000'
    str_9 = 'JCB'
    bool_4 = module_0.is_credit_card(str_8, str_9)
    str_10 = '1234567890123456'
    bool_5 = module_0.is_credit_card(str_10)

def test_case_44():
    str_0 = '4111 1111 1111 1111'
    bool_0 = module_0.is_credit_card(str_0)
    bool_1 = module_0.is_string(str_0)
    str_1 = '4111111111111111'
    bool_2 = module_0.is_credit_card(str_1)
    str_2 = '5111 1111 1111 1111'
    bool_3 = module_0.is_credit_card(str_2)
    str_3 = '5111111111111111'
    bool_4 = module_0.is_credit_card(str_3)
    bool_5 = module_0.is_ip(bool_0)
    str_4 = '::1'
    bool_6 = module_0.is_ip(str_4)

def test_case_45():
    str_0 = 'my.email@the-provider.com'
    bool_0 = module_0.is_email(str_0)
    str_1 = '@gmail.om'
    bool_1 = module_0.is_email(str_1)
    str_2 = 'my.email@'
    bool_2 = module_0.is_email(str_2)
    str_3 = 'my..email@the-provider.com'
    bool_3 = module_0.is_email(str_3)
    bool_4 = module_0.is_email(bool_2)
    bool_5 = module_0.is_email(str_3)
    bool_6 = module_0.is_email(bool_0)
    bool_7 = module_0.is_email(str_2)
    bool_8 = module_0.is_email(str_1)
    str_4 = 'test@domain..com'
    bool_9 = module_0.is_email(str_4)

def test_case_46():
    str_0 = 'my.email@the-provider.com'
    bool_0 = module_0.is_email(str_0)
    str_1 = '@gmail.com'
    bool_1 = module_0.is_email(str_1)
    str_2 = 'my.email@'
    bool_2 = module_0.is_email(str_2)
    str_3 = 'my..email@the-provider.com'
    bool_3 = module_0.is_email(str_3)
    str_4 = 'my.email@the..provider.com'
    bool_4 = module_0.is_email(str_4)
    str_5 = 'my.email@the-provider..com'
    bool_5 = module_0.is_email(str_5)
    str_6 = 'my.email@the-provider.com.'
    bool_6 = module_0.is_email(str_6)
    str_7 = 'my.email@the-provider.com '
    bool_7 = module_0.is_email(str_7)
    str_8 = 'my.email@the-provider.com\n'
    bool_8 = module_0.is_email(str_8)
    str_9 = 'my.email\n@the-provider.com'
    bool_9 = module_0.is_email(str_9)
    str_10 = 'my.email@the-provider.com@the-provider.com'
    bool_10 = module_0.is_email(str_10)
    str_11 = '"my email"@the-provider.com'
    bool_11 = module_0.is_email(str_11)
    bool_12 = module_0.is_email(str_8)

def test_case_47():
    str_0 = 'http://www.example.com'
    bool_0 = module_0.is_url(str_0)
    str_1 = 'https://www.example.com'
    bool_1 = module_0.is_url(str_1)
    str_2 = 'ftp://example.com'
    str_3 = 'http'
    str_4 = 'https'
    str_5 = [str_3, str_4]
    bool_2 = module_0.is_url(str_2, str_5)
    str_6 = 'invalid_url'
    bool_3 = module_0.is_url(str_6)
    str_7 = 'All URL tests passed.'
    var_0 = print(str_7)