# Automatically generated by Pynguin.
import docstring_parser.common as module_0

def test_case_0():
    docstring_0 = module_0.Docstring()

def test_case_1():
    list_0 = None
    str_0 = 'sq$YX&2gAl'
    docstring_meta_0 = module_0.DocstringMeta(list_0, str_0)

def test_case_2():
    list_0 = None
    str_0 = 'deprecated'
    list_1 = []
    parse_error_0 = module_0.ParseError(*list_1)
    int_0 = 3
    docstring_param_0 = module_0.DocstringParam(list_0, str_0, str_0, str_0, int_0, str_0)
    docstring_meta_0 = module_0.DocstringMeta(list_0, str_0)

def test_case_3():
    list_0 = []
    parse_error_0 = module_0.ParseError()
    str_0 = 'lG$\rJd`;'
    bool_0 = True
    docstring_returns_0 = module_0.DocstringReturns(list_0, parse_error_0, str_0, bool_0)

def test_case_4():
    str_0 = 'KtyIY'
    str_1 = 'z,\x0bX`Qf#6cU]\tE*;9#\t\\'
    str_2 = 'H9#\x0b^u'
    list_0 = [str_0, str_1, str_2]
    docstring_raises_0 = module_0.DocstringRaises(list_0, str_2, str_1)

def test_case_5():
    str_0 = 'Setup sections.\n\n        :param sections: Recognized sections or None to defaults.\n        :param title_colon: require colon after section title.\n        '
    list_0 = [str_0, str_0, str_0, str_0]
    docstring_deprecated_0 = module_0.DocstringDeprecated(list_0, str_0, str_0)