# Automatically generated by Pynguin.
import pytutils.env as module_0

def test_case_0():
    generator_0 = module_0.parse_env_file_contents()

def test_case_1():
    str_0 = 'BT@zr}^\x0cY\x0c \\WN{'
    str_1 = module_0.expand(str_0)

def test_case_2():
    str_0 = 'Gy2=\'"nS^!['
    ordered_dict_0 = module_0.load_env_file(str_0)

def test_case_3():
    str_0 = 'Gy2=\'"nS^!['
    list_0 = [str_0, str_0, str_0]
    ordered_dict_0 = module_0.load_env_file(list_0)

def test_case_4():
    str_0 = 'VAR1=value1'
    str_1 = 'VAR2=value2'
    str_2 = "VAR3='value3'"
    str_3 = 'VAR4="value 4"'
    str_4 = 'VAR5=some\\value'
    str_5 = [str_0, str_1, str_2, str_3, str_4]
    generator_0 = module_0.parse_env_file_contents(str_5)
    var_0 = list(generator_0)