# Automatically generated by Pynguin.
import pytutils.env as module_0

def test_case_0():
    try:
        str_0 = 'Gy2=\'"nS^!['
        list_0 = [str_0, str_0, str_0]
        mutable_mapping_0 = None
        ordered_dict_0 = module_0.load_env_file(list_0, mutable_mapping_0)
        generator_0 = module_0.parse_env_file_contents()
        generator_1 = module_0.parse_env_file_contents(generator_0)
        str_1 = '\t{;4\x0c*J9EkEHC{grj'
        str_2 = module_0.expand(str_1)
        optional_0 = None
        generator_2 = module_0.parse_env_file_contents(optional_0)
        iterable_0 = None
        ordered_dict_1 = module_0.load_env_file(iterable_0)
    except BaseException:
        pass