# Automatically generated by Pynguin.
import typed_ast._ast3 as module_0
import py_backwards.transformers.six_moves as module_1

def test_case_0():
    a_s_t_0 = module_0.AST()
    six_moves_transformer_0 = module_1.SixMovesTransformer(a_s_t_0)
    six_moves_transformer_1 = None
    dict_0 = {}
    tuple_0 = ()
    moved_module_0 = module_1.MovedModule(dict_0, tuple_0, dict_0)
    six_moves_transformer_2 = module_1.SixMovesTransformer(a_s_t_0)
    moved_attribute_0 = module_1.MovedAttribute(six_moves_transformer_0, six_moves_transformer_0, six_moves_transformer_1)