# Automatically generated by Pynguin.
import cookiecutter.zipfile as module_0
import tempfile as module_1

def test_case_0():
    try:
        str_0 = 'GsWUFM'
        int_0 = -2448
        var_0 = module_0.unzip(str_0, int_0)
    except BaseException:
        pass

def test_case_1():
    try:
        str_0 = 'test.zip'
        bool_0 = False
        var_0 = module_0.unzip(str_0, bool_0)
    except BaseException:
        pass

def test_case_2():
    try:
        str_0 = "M\\\tz0\\r~'>aqYqY]"
        bool_0 = False
        var_0 = module_0.unzip(str_0, bool_0)
    except BaseException:
        pass

def test_case_3():
    try:
        str_0 = 'https://example.com/sample.zip'
        bool_0 = True
        var_0 = module_1.gettempdir()
        var_1 = module_0.unzip(str_0, bool_0, var_0, bool_0, bool_0)
    except BaseException:
        pass

def test_case_4():
    try:
        str_0 = 'l}?ooP<;c~m\x0bU\nx/nD'
        dict_0 = {str_0: str_0, str_0: str_0, str_0: str_0}
        var_0 = module_0.unzip(str_0, dict_0, str_0)
    except BaseException:
        pass