# Automatically generated by Pynguin.
import pysnooper.tracer as module_0

def test_case_0():
    try:
        dict_0 = {}
        set_0 = None
        bool_0 = True
        unavailable_source_0 = module_0.UnavailableSource(**dict_0)
        var_0 = unavailable_source_0.__getitem__(bool_0)
        tracer_0 = module_0.Tracer(set_0)
        unavailable_source_1 = module_0.UnavailableSource()
        var_1 = tracer_0.__enter__()
        str_0 = ';=\x0c'
        float_0 = None
        tuple_0 = (str_0, float_0, unavailable_source_0)
        dict_1 = {var_0: unavailable_source_1, var_0: tracer_0, unavailable_source_1: var_1, float_0: tuple_0}
        list_0 = []
        file_writer_0 = module_0.FileWriter(list_0, dict_0)
        tracer_1 = module_0.Tracer(dict_0, tuple_0, set_0, dict_1, file_writer_0, list_0)
    except BaseException:
        pass

def test_case_1():
    try:
        int_0 = 2363
        str_0 = 'PathLike'
        var_0 = module_0.get_write_function(int_0, str_0)
    except BaseException:
        pass

def test_case_2():
    try:
        str_0 = '`EO5kVVei,C($|^(G'
        int_0 = 1959
        bytes_0 = b'\x7fV\xec\xbf\xde\xfb\x97'
        list_0 = [int_0, str_0]
        tracer_0 = module_0.Tracer(str_0, int_0, bytes_0, list_0)
    except BaseException:
        pass

def test_case_3():
    try:
        unavailable_source_0 = module_0.UnavailableSource()
        list_0 = [unavailable_source_0]
        set_0 = {unavailable_source_0}
        tracer_0 = module_0.Tracer(unavailable_source_0, list_0, set_0)
    except BaseException:
        pass

def test_case_4():
    try:
        float_0 = -1407.0
        str_0 = 'zZ6O\nD"`q)t\\>.@;'
        file_writer_0 = module_0.FileWriter(str_0, float_0)
        var_0 = file_writer_0.write(float_0)
    except BaseException:
        pass

def test_case_5():
    try:
        float_0 = 1042.1972
        bool_0 = False
        file_writer_0 = module_0.FileWriter(float_0, bool_0)
        list_0 = [bool_0, file_writer_0, float_0, bool_0]
        float_1 = -2314.54107
        str_0 = "<'G^=\t$"
        tracer_0 = None
        dict_0 = {float_1: float_1, tracer_0: tracer_0, file_writer_0: file_writer_0}
        file_writer_1 = module_0.FileWriter(float_0, dict_0)
        var_0 = file_writer_1.write(str_0)
        unavailable_source_0 = module_0.UnavailableSource(*list_0)
    except BaseException:
        pass

def test_case_6():
    try:
        int_0 = None
        set_0 = set()
        dict_0 = None
        bytes_0 = b'"\xe4\xb2\xad\x00+;\xd9\xb3\x1b|l09\x05\xb0w'
        tracer_0 = module_0.Tracer(int_0, set_0, dict_0, bytes_0)
    except BaseException:
        pass

def test_case_7():
    try:
        tracer_0 = module_0.Tracer()
        str_0 = '<ast>'
        var_0 = tracer_0.__call__(str_0)
    except BaseException:
        pass

def test_case_8():
    try:
        set_0 = None
        tracer_0 = module_0.Tracer(set_0)
        unavailable_source_0 = module_0.UnavailableSource()
        var_0 = tracer_0.__enter__()
        bytes_0 = b'\xb3\x0ek\xcc\x0b]~\xbd\xa5sA\x0bu\xfa,\xbd\x1e\xb8\x17S'
        file_writer_0 = module_0.FileWriter(var_0, set_0)
        var_1 = file_writer_0.write(bytes_0)
    except BaseException:
        pass

def test_case_9():
    try:
        str_0 = 'return'
        dict_0 = {str_0: str_0, str_0: str_0, str_0: str_0, str_0: str_0}
        file_writer_0 = module_0.FileWriter(dict_0, dict_0)
        dict_1 = {str_0: str_0, str_0: file_writer_0}
        tracer_0 = module_0.Tracer(file_writer_0, dict_1, str_0)
    except BaseException:
        pass

def test_case_10():
    try:
        dict_0 = {}
        set_0 = None
        unavailable_source_0 = module_0.UnavailableSource(**dict_0)
        tracer_0 = module_0.Tracer(set_0)
        unavailable_source_1 = module_0.UnavailableSource()
        var_0 = tracer_0.__enter__()
        float_0 = None
        list_0 = []
        bool_0 = True
        file_writer_0 = module_0.FileWriter(bool_0, list_0)
        str_0 = "!U'0m`H"
        float_1 = -1858.08
        list_1 = [float_1, float_0, bool_0]
        int_0 = None
        tracer_1 = module_0.Tracer(str_0, unavailable_source_1, list_1, dict_0, file_writer_0, list_1, int_0)
    except BaseException:
        pass

def test_case_11():
    try:
        dict_0 = {}
        set_0 = None
        bool_0 = False
        unavailable_source_0 = module_0.UnavailableSource(**dict_0)
        var_0 = unavailable_source_0.__getitem__(bool_0)
        tracer_0 = module_0.Tracer(set_0)
        unavailable_source_1 = module_0.UnavailableSource()
        var_1 = tracer_0.__enter__()
        float_0 = -3943.17
        file_writer_0 = module_0.FileWriter(bool_0, float_0)
        dict_1 = {file_writer_0: unavailable_source_0}
        tracer_1 = module_0.Tracer(tracer_0)
        str_0 = 'exception'
        tracer_2 = module_0.Tracer(set_0, str_0, dict_1)
    except BaseException:
        pass

def test_case_12():
    try:
        tracer_0 = module_0.Tracer()
        var_0 = None
        var_1 = tracer_0.__exit__(var_0, var_0, var_0)
    except BaseException:
        pass

def test_case_13():
    try:
        tracer_0 = module_0.Tracer()
        var_0 = tracer_0.__enter__()
        var_1 = tracer_0.__exit__(var_0, var_0, var_0)
    except BaseException:
        pass

def test_case_14():
    try:
        tracer_0 = module_0.Tracer()
        str_0 = '[l'
        var_0 = tracer_0.__enter__()
        var_1 = tracer_0.__enter__()
        var_2 = tracer_0.__call__(str_0)
    except BaseException:
        pass