# Automatically generated by Pynguin.
import inspect as module_0
import pysnooper.tracer as module_1

def test_case_0():
    var_0 = module_0.currentframe()

def test_case_1():
    tracer_0 = module_1.Tracer()
    var_0 = tracer_0.__enter__()

def test_case_2():
    tracer_0 = module_1.Tracer()

def test_case_3():
    str_0 = '<8wuE'
    float_0 = 2242.5633
    file_writer_0 = module_1.FileWriter(str_0, float_0)