# Automatically generated by Pynguin.
import sty.primitive as module_0

def test_case_0():
    register_0 = module_0.Register()

def test_case_1():
    style_0 = module_0.Style()

def test_case_2():
    register_0 = module_0.Register()
    str_0 = '\n        Sometimes it is useful to disable the formatting for a register-object. You can\n        do so by invoking this method.\n        '
    style_0 = module_0.Style()
    var_0 = register_0.__setattr__(str_0, style_0)
    register_0.unmute()
    register_0.mute()

def test_case_3():
    bool_0 = None
    str_0 = '80k\t;F^|[DW8}'
    register_0 = module_0.Register()
    register_1 = register_0.copy()
    register_1.set_renderfunc(bool_0, str_0)

def test_case_4():
    register_0 = module_0.Register()
    dict_0 = register_0.as_dict()

def test_case_5():
    register_0 = module_0.Register()
    register_1 = register_0.copy()
    tuple_0 = ()
    register_0.set_renderfunc(tuple_0, register_0)
    var_0 = register_1.as_namedtuple()

def test_case_6():
    register_0 = module_0.Register()
    str_0 = '\n        Sometimes it is useful to disable the formatting for a register-object. You can\n        do so by invoking this method.\n        '
    style_0 = module_0.Style()
    var_0 = register_0.__setattr__(str_0, style_0)
    type_0 = None
    str_1 = ''
    dict_0 = {str_1: type_0}
    register_0.set_renderfunc(type_0, dict_0)
    register_1 = module_0.Register()
    var_1 = register_1.as_namedtuple()

def test_case_7():
    style_0 = module_0.Style()
    register_0 = module_0.Register()
    register_0.mute()
    list_0 = []
    str_0 = register_0.__call__(*list_0)
    register_1 = register_0.copy()
    register_2 = module_0.Register()
    register_3 = module_0.Register()
    str_1 = ':s\\zY\x0cr|_1'
    var_0 = register_0.__setattr__(str_1, style_0)
    register_0.unmute()
    register_2.mute()

def test_case_8():
    register_0 = module_0.Register()
    str_0 = '\n        Sometimes it is useful to disable the formatting for a register-object. You can\n        do so by invoking this method.\n        '
    style_0 = module_0.Style()
    var_0 = register_0.__setattr__(str_0, style_0)
    type_0 = None
    str_1 = ''
    dict_0 = {str_1: type_0}
    register_0.set_renderfunc(type_0, dict_0)
    register_0.set_eightbit_call(type_0)
    register_1 = module_0.Register()
    var_1 = register_1.as_namedtuple()