# Automatically generated by Pynguin.
import sty.primitive as module_0

def test_case_0():
    try:
        register_0 = module_0.Register()
        str_0 = 'E$gZJ;\r-ei,'
        list_0 = [str_0, register_0, str_0, str_0]
        style_0 = module_0.Style(*list_0)
        var_0 = register_0.__setattr__(str_0, style_0)
    except BaseException:
        pass

def test_case_1():
    try:
        str_0 = None
        list_0 = [str_0]
        register_0 = module_0.Register()
        register_1 = register_0.copy()
        register_2 = register_1.copy()
        str_1 = register_2.__call__(*list_0)
    except BaseException:
        pass

def test_case_2():
    try:
        register_0 = module_0.Register()
        register_0.unmute()
        register_1 = register_0.copy()
        str_0 = register_1.__call__()
        set_0 = {register_1}
        register_0.set_rgb_call(set_0)
    except BaseException:
        pass

def test_case_3():
    try:
        list_0 = []
        style_0 = module_0.Style(*list_0)
        register_0 = module_0.Register()
        int_0 = -2713
        list_1 = [int_0, int_0, int_0]
        str_0 = register_0.__call__(*list_1)
        int_1 = 2
        list_2 = [int_1, int_1]
        str_1 = 'X/toE+P&P,s\x0c9jw\\PD'
        dict_0 = {str_1: style_0}
        str_2 = register_0.__call__(*list_2, **dict_0)
        register_1 = module_0.Register()
        list_3 = None
        str_3 = register_0.__call__()
        list_4 = [register_0, register_0, list_3, register_0]
        register_2 = register_0.copy()
        style_1 = module_0.Style(*list_4)
        style_2 = module_0.Style(*list_3)
    except BaseException:
        pass

def test_case_4():
    try:
        register_0 = module_0.Register()
        var_0 = register_0.as_namedtuple()
        str_0 = '!{~H;1z>H'
        str_1 = ''
        list_0 = [str_0, str_1, str_1]
        tuple_0 = (list_0,)
        register_0.set_eightbit_call(tuple_0)
    except BaseException:
        pass

def test_case_5():
    try:
        str_0 = 'dXDXHsTR|qxD*'
        register_0 = module_0.Register()
        register_0.set_rgb_call(str_0)
    except BaseException:
        pass

def test_case_6():
    try:
        register_0 = module_0.Register()
        str_0 = '\n        Sometimes it is useGul to disable the formatting for a register-object. You can\n  Q     do so by invoking this method.\n        '
        style_0 = module_0.Style()
        var_0 = register_0.__setattr__(str_0, style_0)
        register_1 = register_0.copy()
        var_1 = register_1.as_namedtuple()
    except BaseException:
        pass

def test_case_7():
    try:
        list_0 = []
        style_0 = module_0.Style(*list_0)
        register_0 = module_0.Register()
        int_0 = 2
        list_1 = [int_0]
        str_0 = 'X/toE+P&P,s\x0c9jw\\PD'
        dict_0 = {str_0: style_0}
        str_1 = register_0.__call__(*list_1, **dict_0)
    except BaseException:
        pass

def test_case_8():
    try:
        register_0 = module_0.Register()
        str_0 = register_0.__call__()
        register_1 = module_0.Register()
        var_0 = register_1.as_namedtuple()
        style_0 = None
        list_0 = [style_0]
        register_2 = module_0.Register()
        bool_0 = False
        str_1 = 'm'
        register_2.set_renderfunc(bool_0, str_1)
        dict_0 = register_2.as_dict()
        style_1 = module_0.Style(*list_0)
        type_0 = None
        list_1 = []
        register_1.set_renderfunc(type_0, list_1)
        register_2.mute()
        register_3 = module_0.Register()
        str_2 = register_2.__call__()
        register_1.set_rgb_call(type_0)
        register_4 = register_0.copy()
        register_3.set_renderfunc(type_0, list_1)
        var_1 = register_4.as_namedtuple()
        register_1.set_rgb_call(type_0)
        int_0 = 0
        register_5 = register_0.copy()
        register_3.set_renderfunc(type_0, int_0)
        list_2 = []
        str_3 = '$dkee:'
        style_2 = style_1.__new__(list_2, value=str_3)
    except BaseException:
        pass

def test_case_9():
    try:
        register_0 = module_0.Register()
        str_0 = '\n        Sometimes it is useful to disable the formatting for a register-object. You can\n        do so by invoking this method.\n        '
        str_1 = register_0.__call__()
        list_0 = [str_1, str_0, str_1]
        dict_0 = {}
        style_0 = module_0.Style(*list_0, **dict_0)
        register_1 = module_0.Register()
        dict_1 = register_1.as_dict()
        register_2 = module_0.Register()
        register_3 = register_2.copy()
        register_4 = module_0.Register()
        register_5 = register_4.copy()
        register_6 = register_5.copy()
        register_6.mute()
        register_7 = register_3.copy()
        register_6.unmute()
        int_0 = 93
        register_8 = register_1.copy()
        str_2 = "1r!C&9'@\t<\rD"
        list_1 = [int_0]
        str_3 = register_5.__call__(*list_1)
        var_0 = register_5.__setattr__(str_2, style_0)
    except BaseException:
        pass