# Automatically generated by Pynguin.
import tornado.escape as module_0

def test_case_0():
    try:
        bytes_0 = b'\xc7 \x88$\xc8\x84%v\xb0\x0cG2Rw\x10)u\x1e\x08'
        str_0 = module_0.xhtml_escape(bytes_0)
    except BaseException:
        pass

def test_case_1():
    try:
        bytes_0 = b'\xb6\xea{\xc2\xd6B?\x7f\\\xd3H\xeak'
        any_0 = module_0.json_decode(bytes_0)
    except BaseException:
        pass

def test_case_2():
    try:
        bytes_0 = None
        str_0 = module_0.url_escape(bytes_0)
    except BaseException:
        pass

def test_case_3():
    try:
        bytes_0 = b'6\xd3\x0b:\xc8\xee\x1fU"\xc2\x83\r\xe2'
        var_0 = module_0.url_unescape(bytes_0)
    except BaseException:
        pass

def test_case_4():
    try:
        bytes_0 = b'\xa8\x8a\x02;/!\x85}\x8fYl\xabv\xbayn\xb01p'
        bool_0 = True
        bool_1 = True
        str_0 = module_0.linkify(bytes_0, bool_0, bool_1)
    except BaseException:
        pass

def test_case_5():
    try:
        bytes_0 = b''
        optional_0 = module_0.utf8(bytes_0)
        str_0 = module_0.xhtml_escape(bytes_0)
        optional_1 = module_0.utf8(bytes_0)
        optional_2 = module_0.to_unicode(bytes_0)
        dict_0 = module_0.parse_qs_bytes(str_0)
        str_1 = None
        var_0 = module_0.url_unescape(str_1, str_1)
    except BaseException:
        pass

def test_case_6():
    try:
        float_0 = -445.9864
        bool_0 = True
        str_0 = 'Dr1_d,7/I#;'
        bool_1 = None
        var_0 = module_0.url_unescape(str_0, bool_1)
        list_0 = [float_0, bool_0, float_0, bool_0]
        any_0 = module_0.recursive_unicode(list_0)
        bytes_0 = b'J'
        str_1 = module_0.url_escape(bytes_0, bool_0)
        bool_2 = False
        var_1 = module_0.url_unescape(str_0, bool_2)
        any_1 = module_0.json_decode(str_0)
    except BaseException:
        pass

def test_case_7():
    try:
        float_0 = 0.5
        optional_0 = module_0.to_unicode(float_0)
    except BaseException:
        pass

def test_case_8():
    try:
        bool_0 = True
        optional_0 = module_0.utf8(bool_0)
    except BaseException:
        pass

def test_case_9():
    try:
        str_0 = "7'6+@6e\\@Tqz_\n%"
        optional_0 = module_0.to_unicode(str_0)
        bytes_0 = b'\n\x82eHq\x85*\xbe=\xce\x93\xf9\x19\x80.\x1dU\x03'
        bool_0 = True
        optional_1 = module_0.utf8(str_0)
        str_1 = module_0.url_escape(bytes_0, bool_0)
        bool_1 = True
        dict_0 = module_0.parse_qs_bytes(bytes_0)
        str_2 = '6|$Yj?Z#,6;L'
        str_3 = module_0.squeeze(str_2)
        optional_2 = module_0.to_unicode(str_0)
        optional_3 = module_0.utf8(str_0)
        str_4 = 'As9Vdci"D6xmvn/v=qvD'
        list_0 = [str_4]
        optional_4 = module_0.utf8(str_4)
        any_0 = module_0.recursive_unicode(str_1)
        str_5 = module_0.linkify(str_0, bool_1, str_1, list_0)
        str_6 = module_0.linkify(str_1)
        str_7 = 'Q#C/=f2A7<~/[]&$'
        set_0 = {optional_0, str_2, str_7, str_6}
        tuple_0 = (str_7, set_0)
        any_1 = module_0.recursive_unicode(tuple_0)
        str_8 = module_0.xhtml_escape(bytes_0)
    except BaseException:
        pass

def test_case_10():
    try:
        str_0 = 'Hello http://tornadoweb.org!'
        str_1 = module_0.linkify(str_0)
        str_2 = module_0.linkify(str_1)
        str_3 = module_0.xhtml_escape(str_1)
        bool_0 = True
        str_4 = module_0.linkify(str_3, bool_0)
        str_5 = module_0.linkify(str_4, bool_0)
        bytes_0 = b'w\x81i\x9e'
        bool_1 = True
        str_6 = module_0.linkify(bytes_0, bool_1)
    except BaseException:
        pass