# Automatically generated by Pynguin.
import tornado.escape as module_0

def test_case_0():
    str_0 = 'o|S'
    str_1 = module_0.json_encode(str_0)

def test_case_1():
    str_0 = '100-continue'
    str_1 = module_0.xhtml_unescape(str_0)

def test_case_2():
    str_0 = 'Turns on formatted logging output as configured.\n\n    This is called automatically by `tornado.options.parse_command_line`\n    and `tornado.options.parse_config_file`.\n    '
    str_1 = module_0.squeeze(str_0)

def test_case_3():
    bytes_0 = b'\xe82#\xbb\xcf5w\xff\xab'
    dict_0 = module_0.parse_qs_bytes(bytes_0)

def test_case_4():
    str_0 = '%:z'
    str_1 = module_0.xhtml_escape(str_0)
    optional_0 = module_0.utf8(str_1)
    str_2 = "|o)?q['WrC=^x"
    str_3 = module_0.json_encode(str_1)
    bool_0 = False
    optional_1 = module_0.utf8(str_2)
    optional_2 = module_0.to_unicode(str_2)
    dict_0 = module_0.parse_qs_bytes(str_2, bool_0)
    str_4 = 'upgrade'
    str_5 = module_0.squeeze(str_4)
    str_6 = module_0.xhtml_unescape(str_4)
    any_0 = module_0.recursive_unicode(str_5)
    str_7 = module_0.linkify(str_6)

def test_case_5():
    str_0 = 'd|R%+'
    optional_0 = module_0.utf8(str_0)

def test_case_6():
    bool_0 = True
    any_0 = module_0.recursive_unicode(bool_0)

def test_case_7():
    float_0 = -445.9864
    bool_0 = True
    list_0 = [float_0, bool_0, float_0, bool_0]
    any_0 = module_0.recursive_unicode(list_0)
    bytes_0 = b'\xdeJ'
    dict_0 = module_0.parse_qs_bytes(bytes_0)
    bytes_1 = b'\xb3&\xc1,\xbc\x84.\xb4XZ'
    str_0 = module_0.url_escape(bytes_1)

def test_case_8():
    bytes_0 = b'"'
    optional_0 = module_0.utf8(bytes_0)
    bytes_1 = b'\x89\xfb\xeb\x8a\x14\x04\xb91\x9f(\x0c\xc5|\x82l\xad'
    bool_0 = True
    dict_0 = module_0.parse_qs_bytes(bytes_1, bool_0)
    str_0 = module_0.xhtml_escape(bytes_0)
    optional_1 = module_0.utf8(bytes_0)
    optional_2 = module_0.to_unicode(bytes_0)
    var_0 = module_0.url_unescape(str_0)
    str_1 = module_0.xhtml_unescape(str_0)
    any_0 = module_0.recursive_unicode(dict_0)
    bool_1 = True
    str_2 = 'L/Y>T5nw@Idrr*nWUqt'
    list_0 = [str_0, str_2, str_2, str_0]
    str_3 = module_0.linkify(str_0, bool_1, str_1, list_0)

def test_case_9():
    str_0 = 'Check out www.example.com'
    str_1 = module_0.linkify(str_0)

def test_case_10():
    bytes_0 = b'"'
    str_0 = module_0.xhtml_escape(bytes_0)
    optional_0 = module_0.to_unicode(bytes_0)
    str_1 = module_0.xhtml_unescape(str_0)

def test_case_11():
    str_0 = 'Turns on formatted logging output as configured.\n\n    This is called automatically by `tornado.options.parse_command_line`\n    and `tornado.options.parse_config_file`.\n    '
    bool_0 = None
    str_1 = module_0.url_escape(str_0, bool_0)

def test_case_12():
    str_0 = "7'6+@6e\\@Tqz_\n%"
    optional_0 = module_0.to_unicode(str_0)
    str_1 = module_0.linkify(str_0, str_0)
    optional_1 = module_0.to_unicode(str_1)
    dict_0 = module_0.parse_qs_bytes(str_0)
    str_2 = module_0.xhtml_unescape(str_1)

def test_case_13():
    bytes_0 = b'"'
    optional_0 = module_0.utf8(bytes_0)
    str_0 = module_0.xhtml_escape(bytes_0)
    optional_1 = module_0.utf8(bytes_0)
    optional_2 = module_0.to_unicode(bytes_0)
    dict_0 = module_0.parse_qs_bytes(str_0)
    str_1 = 'upgrade'
    var_0 = module_0.url_unescape(str_0)
    str_2 = module_0.squeeze(str_1)
    str_3 = module_0.xhtml_unescape(str_2)
    any_0 = module_0.recursive_unicode(dict_0)
    str_4 = module_0.linkify(str_3)

def test_case_14():
    str_0 = "go'I.QuB"
    str_1 = module_0.xhtml_unescape(str_0)
    str_2 = None
    optional_0 = module_0.utf8(str_2)
    bool_0 = True
    str_3 = module_0.url_escape(str_0, bool_0)
    str_4 = '9fUotkyzt[WLf'
    bool_1 = False
    var_0 = module_0.url_unescape(str_4, str_4, bool_1)

def test_case_15():
    str_0 = "7'6+@6e\\@Tqz_\n%"
    optional_0 = module_0.to_unicode(str_0)
    optional_1 = module_0.to_unicode(str_0)
    str_1 = module_0.xhtml_escape(str_0)
    str_2 = module_0.linkify(str_0, str_1)
    str_3 = module_0.squeeze(str_0)
    any_0 = module_0.recursive_unicode(str_2)
    str_4 = '\x0bg\x0cx1!hD;g9XW*/0\n-j'
    str_5 = module_0.xhtml_escape(str_4)
    optional_2 = module_0.to_unicode(str_0)
    dict_0 = module_0.parse_qs_bytes(str_3)
    str_6 = module_0.xhtml_unescape(str_0)
    none_type_0 = None
    bool_0 = False
    var_0 = module_0.url_unescape(str_6, none_type_0, bool_0)
    any_1 = module_0.recursive_unicode(str_2)

def test_case_16():
    str_0 = 'Hello, this is a test http://examplH.com/path/to/resource'
    str_1 = module_0.linkify(str_0, str_0)

def test_case_17():
    str_0 = 'Hello http://tornadoweb.org!'
    str_1 = module_0.linkify(str_0)
    str_2 = 'Hello ftp://ftp.example.com!'
    str_3 = 'Hello, this is a test http://examplH.com/path/to/resource'
    str_4 = module_0.linkify(str_2, str_3)

def test_case_18():
    str_0 = 'Hello http://tornadoweb.org!'
    str_1 = module_0.linkify(str_0)

def test_case_19():
    str_0 = 'Hello http://tornadoweb.org!'
    str_1 = module_0.linkify(str_0)
    str_2 = 'Hello www.tornadoweb.org!'
    str_3 = module_0.linkify(str_2)
    str_4 = 'Hello www.example.com!'
    bool_0 = True
    str_5 = '2\t]C'
    str_6 = 'O].|63\r@D:'
    list_0 = [str_0, str_5, str_6]
    str_7 = module_0.linkify(str_0, bool_0, str_4, list_0)
    str_8 = module_0.linkify(str_0, list_0)
    str_9 = module_0.linkify(str_1)

def test_case_20():
    str_0 = 'Check out http://example.com and www.example.com'
    bool_0 = True
    str_1 = module_0.linkify(str_0, bool_0)
    var_0 = print(str_1)

def test_case_21():
    str_0 = "7'6+@6e\\@Tqz_\n%"
    optional_0 = module_0.to_unicode(str_0)
    bytes_0 = b'\n\x82eHq\x85*\xbe=\xce\xc3\xf9\x19\x80.\x1dU\x90\x0b'
    bool_0 = True
    str_1 = module_0.url_escape(bytes_0, bool_0)
    dict_0 = module_0.parse_qs_bytes(bytes_0)
    optional_1 = module_0.utf8(str_0)
    str_2 = 'Visit <a href="http://www.example.com">www.example.com</a> for more!'
    str_3 = 'Check out http://example.com/some/long/url/that/needs/to/be/shortened'
    bool_1 = True
    str_4 = module_0.linkify(str_2, bool_1, str_3, bool_0)