# Automatically generated by Pynguin.
import tqdm.contrib.logging as module_0
import logging as module_1

def test_case_0():
    tqdm_logging_handler_0 = module_0._TqdmLoggingHandler()

def test_case_1():
    tqdm_logging_handler_0 = module_0._TqdmLoggingHandler()
    var_0 = tqdm_logging_handler_0.emit(tqdm_logging_handler_0)

def test_case_2():
    tqdm_logging_handler_0 = module_0._TqdmLoggingHandler()
    stream_handler_0 = module_1.StreamHandler()
    str_0 = 'xQxC'
    var_0 = tqdm_logging_handler_0.emit(str_0)
    str_1 = '+'
    bytes_0 = None
    var_1 = module_0.logging_redirect_tqdm(bytes_0)
    int_0 = 1235
    dict_0 = {var_0: str_0, int_0: str_0}
    float_0 = 4740.6
    dict_1 = {}
    list_0 = [dict_1, dict_1, float_0, tqdm_logging_handler_0]
    tuple_0 = (list_0, stream_handler_0, tqdm_logging_handler_0, list_0)
    list_1 = [var_0, tuple_0]
    list_2 = [str_1]
    float_1 = None
    log_record_0 = module_1.LogRecord(dict_0, float_0, dict_1, dict_1, list_1, list_2, float_1, list_2)
    list_3 = [tqdm_logging_handler_0, log_record_0]
    list_4 = []
    formatter_0 = None
    log_record_1 = module_1.LogRecord(int_0, str_1, list_3, dict_1, list_4, dict_1, formatter_0, int_0)
    var_2 = tqdm_logging_handler_0.emit(log_record_1)
    tqdm_logging_handler_1 = module_0._TqdmLoggingHandler()
    var_3 = tqdm_logging_handler_1.emit(list_2)