# Automatically generated by Pynguin.
import thonny.roughparse as module_0

def test_case_0():
    float_0 = -2201.483411
    list_0 = [float_0]
    rough_parser_0 = module_0.RoughParser(float_0, list_0)

def test_case_1():
    str_0 = 'a'
    var_0 = ord(str_0)
    str_1 = 'b'
    var_1 = ord(str_1)
    str_2 = 'x'
    var_2 = ord(str_2)
    str_3 = 'y'
    var_3 = ord(str_3)
    var_4 = {var_0: var_2, var_1: var_3}
    str_4 = '_'
    var_5 = ord(str_4)
    string_translate_pseudo_mapping_0 = module_0.StringTranslatePseudoMapping(var_4, var_5)
    var_6 = ord(str_0)
    var_7 = ord(str_1)
    var_8 = list(string_translate_pseudo_mapping_0)

def test_case_2():
    int_0 = 1
    int_1 = 2
    str_0 = 'a'
    str_1 = 'b'
    str_2 = {int_0: str_0, int_1: str_1}
    str_3 = 'default'
    string_translate_pseudo_mapping_0 = module_0.StringTranslatePseudoMapping(str_2, str_3)
    var_0 = string_translate_pseudo_mapping_0.get(int_0)
    var_1 = string_translate_pseudo_mapping_0.get(int_1)
    int_2 = 3
    var_2 = string_translate_pseudo_mapping_0.get(int_2)
    str_4 = 'another_default'
    var_3 = string_translate_pseudo_mapping_0.get(int_2, str_4)