# Automatically generated by Pynguin.
import thonny.roughparse as module_0

def test_case_0():
    try:
        int_0 = 2183
        str_0 = 'dXy~\rrkY(HB'
        hyper_parser_0 = module_0.HyperParser(int_0, str_0)
    except BaseException:
        pass

def test_case_1():
    try:
        bytes_0 = b'\xf4E\xcc[k&\x89\xa1/\xfaHm\xcd\xf0'
        string_translate_pseudo_mapping_0 = None
        set_0 = {bytes_0, bytes_0, string_translate_pseudo_mapping_0}
        str_0 = 'WxrEt$'
        rough_parser_0 = module_0.RoughParser(set_0, str_0)
        rough_parser_1 = module_0.RoughParser(bytes_0, rough_parser_0)
        var_0 = rough_parser_1.get_num_lines_in_stmt()
    except BaseException:
        pass

def test_case_2():
    try:
        list_0 = []
        rough_parser_0 = module_0.RoughParser(list_0, list_0)
        str_0 = ''
        var_0 = rough_parser_0.set_str(str_0)
        var_1 = rough_parser_0.get_continuation_type()
        var_2 = rough_parser_0.get_base_indent_string()
        var_3 = rough_parser_0.find_good_parse_start()
        var_4 = rough_parser_0.get_last_open_bracket_pos()
        var_5 = rough_parser_0.get_last_stmt_bracketing()
        var_6 = rough_parser_0.compute_backslash_indent()
    except BaseException:
        pass

def test_case_3():
    try:
        list_0 = []
        rough_parser_0 = module_0.RoughParser(list_0, list_0)
        str_0 = ''
        var_0 = rough_parser_0.set_str(str_0)
        var_1 = rough_parser_0.compute_bracket_indent()
    except BaseException:
        pass

def test_case_4():
    try:
        list_0 = []
        rough_parser_0 = module_0.RoughParser(list_0, list_0)
        str_0 = ''
        var_0 = rough_parser_0.set_str(str_0)
        var_1 = rough_parser_0.compute_backslash_indent()
    except BaseException:
        pass

def test_case_5():
    try:
        list_0 = []
        rough_parser_0 = module_0.RoughParser(list_0, list_0)
        str_0 = ''
        var_0 = rough_parser_0.set_str(str_0)
        var_1 = rough_parser_0.get_base_indent_string()
        var_2 = rough_parser_0.find_good_parse_start()
        var_3 = rough_parser_0.get_last_open_bracket_pos()
        var_4 = rough_parser_0.get_last_stmt_bracketing()
        var_5 = rough_parser_0.compute_backslash_indent()
    except BaseException:
        pass

def test_case_6():
    try:
        list_0 = []
        rough_parser_0 = module_0.RoughParser(list_0, list_0)
        str_0 = ''
        var_0 = rough_parser_0.set_str(str_0)
        var_1 = rough_parser_0.get_last_stmt_bracketing()
        var_2 = rough_parser_0.compute_backslash_indent()
    except BaseException:
        pass

def test_case_7():
    try:
        list_0 = []
        rough_parser_0 = module_0.RoughParser(list_0, list_0)
        str_0 = ''
        var_0 = rough_parser_0.set_str(str_0)
        var_1 = rough_parser_0.find_good_parse_start(rough_parser_0)
        var_2 = rough_parser_0.is_block_closer()
        var_3 = rough_parser_0.get_last_open_bracket_pos()
        var_4 = rough_parser_0.get_last_stmt_bracketing()
        var_5 = rough_parser_0.compute_backslash_indent()
    except BaseException:
        pass

def test_case_8():
    try:
        str_0 = ''
        float_0 = -1811.8
        set_0 = {float_0, str_0}
        rough_parser_0 = module_0.RoughParser(float_0, set_0)
        var_0 = rough_parser_0.find_good_parse_start()
    except BaseException:
        pass

def test_case_9():
    try:
        list_0 = []
        rough_parser_0 = module_0.RoughParser(list_0, list_0)
        var_0 = rough_parser_0.is_block_opener()
    except BaseException:
        pass

def test_case_10():
    try:
        list_0 = []
        rough_parser_0 = module_0.RoughParser(list_0, list_0)
        str_0 = ''
        var_0 = rough_parser_0.set_str(str_0)
        var_1 = rough_parser_0.find_good_parse_start(rough_parser_0)
        var_2 = rough_parser_0.get_last_open_bracket_pos()
        var_3 = rough_parser_0.get_last_stmt_bracketing()
        str_1 = 'OSWG'
        var_4 = rough_parser_0.set_str(str_1)
    except BaseException:
        pass

def test_case_11():
    try:
        list_0 = []
        rough_parser_0 = module_0.RoughParser(list_0, list_0)
        str_0 = ''
        var_0 = rough_parser_0.set_str(str_0)
        var_1 = rough_parser_0.get_base_indent_string()
        var_2 = rough_parser_0.compute_bracket_indent()
    except BaseException:
        pass

def test_case_12():
    try:
        str_0 = 'headings'
        bytes_0 = b''
        rough_parser_0 = module_0.RoughParser(str_0, bytes_0)
        int_0 = 101
        rough_parser_1 = module_0.RoughParser(rough_parser_0, int_0)
        int_1 = -1263
        hyper_parser_0 = module_0.HyperParser(rough_parser_1, int_1)
    except BaseException:
        pass

def test_case_13():
    try:
        list_0 = []
        rough_parser_0 = module_0.RoughParser(list_0, list_0)
        str_0 = '\n'
        var_0 = rough_parser_0.set_str(str_0)
        var_1 = rough_parser_0.get_base_indent_string()
        var_2 = rough_parser_0.find_good_parse_start()
        string_translate_pseudo_mapping_0 = module_0.StringTranslatePseudoMapping(rough_parser_0, rough_parser_0)
    except BaseException:
        pass

def test_case_14():
    try:
        bytes_0 = None
        set_0 = {bytes_0, bytes_0}
        rough_parser_0 = module_0.RoughParser(set_0, set_0)
        float_0 = 810.8884
        var_0 = rough_parser_0.set_lo(float_0)
    except BaseException:
        pass

def test_case_15():
    try:
        list_0 = []
        rough_parser_0 = module_0.RoughParser(list_0, list_0)
        str_0 = ''
        var_0 = rough_parser_0.set_str(str_0)
        var_1 = rough_parser_0.is_block_opener()
        var_2 = rough_parser_0.get_last_stmt_bracketing()
        float_0 = 94.72
        hyper_parser_0 = module_0.HyperParser(float_0, rough_parser_0)
    except BaseException:
        pass

def test_case_16():
    try:
        list_0 = []
        rough_parser_0 = module_0.RoughParser(list_0, list_0)
        str_0 = ''
        var_0 = rough_parser_0.set_str(str_0)
        str_1 = '^B:BC8oIW$9%wq)C&\n>,'
        var_1 = rough_parser_0.find_good_parse_start(str_1)
        var_2 = rough_parser_0.find_good_parse_start(list_0)
        var_3 = rough_parser_0.get_last_stmt_bracketing()
        var_4 = rough_parser_0.compute_backslash_indent()
    except BaseException:
        pass

def test_case_17():
    try:
        list_0 = []
        rough_parser_0 = module_0.RoughParser(list_0, list_0)
        str_0 = ''
        var_0 = rough_parser_0.set_str(str_0)
        bool_0 = False
        var_1 = rough_parser_0.get_last_stmt_bracketing()
        var_2 = rough_parser_0.set_lo(bool_0)
        var_3 = rough_parser_0.compute_bracket_indent()
    except BaseException:
        pass

def test_case_18():
    try:
        list_0 = []
        rough_parser_0 = module_0.RoughParser(list_0, list_0)
        str_0 = ''
        var_0 = rough_parser_0.set_str(str_0)
        var_1 = rough_parser_0.get_base_indent_string()
        var_2 = rough_parser_0.find_good_parse_start()
        var_3 = rough_parser_0.get_last_stmt_bracketing()
        var_4 = rough_parser_0.get_num_lines_in_stmt()
    except BaseException:
        pass