# Automatically generated by Pynguin.
import httpie.plugins.base as module_0

def test_case_0():
    auth_plugin_0 = module_0.AuthPlugin()

def test_case_1():
    auth_plugin_0 = None
    set_0 = {auth_plugin_0, auth_plugin_0}
    converter_plugin_0 = module_0.ConverterPlugin(set_0)
    converter_plugin_1 = module_0.ConverterPlugin(converter_plugin_0)