# Automatically generated by Pynguin.
import httpie.plugins.base as module_0

def test_case_0():
    try:
        str_0 = 'expires'
        str_1 = None
        dict_0 = {str_0: str_0, str_1: str_1, str_1: str_0}
        auth_plugin_0 = module_0.AuthPlugin()
        var_0 = auth_plugin_0.get_auth(dict_0)
    except BaseException:
        pass

def test_case_1():
    try:
        transport_plugin_0 = module_0.TransportPlugin()
        var_0 = transport_plugin_0.get_adapter()
    except BaseException:
        pass

def test_case_2():
    try:
        bytes_0 = b'\xcb(q\x8b\x03\xa4\xae'
        float_0 = 451.35516
        converter_plugin_0 = module_0.ConverterPlugin(float_0)
        var_0 = converter_plugin_0.convert(bytes_0)
    except BaseException:
        pass

def test_case_3():
    try:
        formatter_plugin_0 = module_0.FormatterPlugin()
    except BaseException:
        pass