# Automatically generated by Pynguin.
import flutils.packages as module_0

def test_case_0():
    try:
        version_info_0 = module_0._VersionInfo()
    except BaseException:
        pass

def test_case_1():
    try:
        str_0 = '1.2.3'
        int_0 = 1
        str_1 = '1.3.4'
        int_1 = 0
        str_2 = module_0.bump_version(str_1, int_1)
        str_3 = 'a'
        str_4 = module_0.bump_version(str_2)
        str_5 = module_0.bump_version(str_0, int_0, str_3)
        int_2 = -2752
        str_6 = module_0.bump_version(str_5, int_2)
    except BaseException:
        pass

def test_case_2():
    try:
        str_0 = '1.2.2'
        int_0 = 1
        str_1 = module_0.bump_version(str_0, int_0)
        str_2 = '1.3.4'
        str_3 = '1.2.4a0'
        str_4 = module_0.bump_version(str_2)
        str_5 = module_0.bump_version(str_3, int_0, str_3)
    except BaseException:
        pass

def test_case_3():
    try:
        int_0 = 1
        str_0 = '1.3.4'
        str_1 = 'b'
        str_2 = module_0.bump_version(str_0, int_0, str_1)
        str_3 = module_0.bump_version(str_1)
    except BaseException:
        pass

def test_case_4():
    try:
        int_0 = 1
        str_0 = '1.3.4'
        int_1 = 0
        str_1 = module_0.bump_version(str_0, int_1)
        str_2 = 'a'
        str_3 = module_0.bump_version(str_1, int_0, str_2)
        str_4 = module_0.bump_version(str_1, str_1)
    except BaseException:
        pass

def test_case_5():
    try:
        str_0 = '1.2.2'
        str_1 = module_0.bump_version(str_0)
        str_2 = '1.2.3'
        int_0 = 1
        str_3 = module_0.bump_version(str_2, int_0)
        str_4 = '1.3.4'
        int_1 = -1
        str_5 = module_0.bump_version(str_4, int_1)
        str_6 = 'a'
        str_7 = module_0.bump_version(str_2)
        str_8 = '1.2.4a0'
        str_9 = module_0.bump_version(str_8, str_6)
    except BaseException:
        pass

def test_case_6():
    try:
        str_0 = '1.2.3'
        int_0 = 0
        str_1 = 'a'
        str_2 = module_0.bump_version(str_0)
        str_3 = '1.2.4a0'
        str_4 = 'b'
        str_5 = module_0.bump_version(str_0)
        str_6 = module_0.bump_version(str_3, int_0, str_4)
    except BaseException:
        pass

def test_case_7():
    try:
        str_0 = '1.2.2'
        str_1 = module_0.bump_version(str_0)
        str_2 = '1.2.3'
        int_0 = 2
        str_3 = module_0.bump_version(str_2, int_0)
        str_4 = '1.2.4a0'
        str_5 = 'b'
        str_6 = module_0.bump_version(str_4, int_0, str_5)
        str_7 = '<3f79g@D;'
        str_8 = module_0.bump_version(str_7)
    except BaseException:
        pass

def test_case_8():
    try:
        str_0 = '1.2.2'
        str_1 = module_0.bump_version(str_0)
        int_0 = 2
        str_2 = module_0.bump_version(str_1, int_0)
        str_3 = 'a'
        str_4 = module_0.bump_version(str_0, int_0, str_3)
        str_5 = module_0.bump_version(str_3)
    except BaseException:
        pass