# Automatically generated by Pynguin.
import pypara.accounting.ledger as module_0

def test_case_0():
    try:
        date_range_0 = None
        dict_0 = {}
        var_0 = module_0.build_general_ledger(date_range_0, date_range_0, dict_0)
    except BaseException:
        pass

def test_case_1():
    try:
        date_range_0 = None
        iterable_0 = None
        dict_0 = {}
        read_initial_balances_0 = None
        bytes_0 = b'\x1d\x10\xa3\xe9^Bq\xda\xfa\xbf<a\x9fG\xe6\xa0\xa9\xec\x9d\xdb'
        var_0 = module_0.compile_general_ledger_program(read_initial_balances_0, bytes_0)
        var_1 = module_0.compile_general_ledger_program(read_initial_balances_0, var_0)
        var_2 = module_0.build_general_ledger(date_range_0, iterable_0, dict_0)
    except BaseException:
        pass