# Automatically generated by Pynguin.
import string_utils.generation as module_0

def test_case_0():
    try:
        int_0 = -1833
        str_0 = module_0.random_string(int_0)
    except BaseException:
        pass

def test_case_1():
    try:
        int_0 = -2451
        str_0 = module_0.secure_random_hex(int_0)
    except BaseException:
        pass

def test_case_2():
    try:
        int_0 = 525
        str_0 = module_0.secure_random_hex(int_0)
        int_1 = -1449
        generator_0 = module_0.roman_range(int_0, int_1)
    except BaseException:
        pass

def test_case_3():
    try:
        int_0 = 894
        int_1 = -2585
        generator_0 = module_0.roman_range(int_0, int_0, int_1)
    except BaseException:
        pass

def test_case_4():
    try:
        int_0 = -3353
        int_1 = 191
        str_0 = module_0.random_string(int_1)
        generator_0 = module_0.roman_range(int_0)
    except BaseException:
        pass

def test_case_5():
    try:
        int_0 = None
        generator_0 = module_0.roman_range(int_0)
    except BaseException:
        pass

def test_case_6():
    try:
        str_0 = module_0.uuid()
        int_0 = 11
        str_1 = module_0.random_string(int_0)
        int_1 = 1563
        generator_0 = module_0.roman_range(int_1, int_0)
        str_2 = module_0.secure_random_hex(int_0)
        str_3 = module_0.secure_random_hex(int_0)
        bool_0 = True
        int_2 = 697
        int_3 = 365
        str_4 = module_0.secure_random_hex(int_3)
        str_5 = module_0.secure_random_hex(int_0)
        str_6 = module_0.uuid()
        str_7 = module_0.uuid(bool_0)
        generator_1 = module_0.roman_range(int_3)
        generator_2 = module_0.roman_range(int_2)
        bool_1 = True
        str_8 = module_0.uuid(bool_1)
        int_4 = None
        str_9 = module_0.random_string(int_4)
    except BaseException:
        pass

def test_case_7():
    try:
        int_0 = 2867
        int_1 = 9
        str_0 = module_0.random_string(int_1)
        str_1 = module_0.secure_random_hex(int_0)
        generator_0 = module_0.roman_range(int_0)
        str_2 = module_0.uuid()
        bool_0 = False
        str_3 = module_0.uuid(bool_0)
        str_4 = module_0.uuid()
        int_2 = None
        str_5 = module_0.secure_random_hex(int_2)
    except BaseException:
        pass

def test_case_8():
    try:
        int_0 = 105
        generator_0 = module_0.roman_range(int_0, int_0)
    except BaseException:
        pass

def test_case_9():
    try:
        int_0 = 64
        str_0 = module_0.secure_random_hex(int_0)
        int_1 = 7
        generator_0 = module_0.roman_range(int_1)
        var_0 = list(generator_0)
        generator_1 = module_0.roman_range(int_1, int_0, int_0)
    except BaseException:
        pass

def test_case_10():
    try:
        str_0 = module_0.uuid()
        int_0 = 11
        str_1 = module_0.random_string(int_0)
        int_1 = 1563
        int_2 = 1
        generator_0 = module_0.roman_range(int_1, int_2)
        str_2 = module_0.secure_random_hex(int_0)
        str_3 = module_0.secure_random_hex(int_0)
        bool_0 = True
        str_4 = module_0.random_string(int_2)
        int_3 = 386
        str_5 = module_0.secure_random_hex(int_3)
        str_6 = module_0.secure_random_hex(int_0)
        str_7 = module_0.uuid()
        str_8 = module_0.uuid(bool_0)
        generator_1 = module_0.roman_range(int_3)
        int_4 = 4473
        generator_2 = module_0.roman_range(int_4)
    except BaseException:
        pass

def test_case_11():
    try:
        int_0 = 5
        generator_0 = module_0.roman_range(int_0)
        var_0 = list(generator_0)
        int_1 = 7
        generator_1 = module_0.roman_range(int_1)
        var_1 = list(generator_1)
        int_2 = 992
        int_3 = -1
        generator_2 = module_0.roman_range(int_2, int_1, int_3)
    except BaseException:
        pass