# Automatically generated by Pynguin.
import string_utils.generation as module_0

def test_case_0():
    str_0 = module_0.uuid()

def test_case_1():
    int_0 = 5
    generator_0 = module_0.roman_range(int_0)
    var_0 = list(generator_0)
    int_1 = 7
    generator_1 = module_0.roman_range(int_1)
    var_1 = list(generator_1)
    int_2 = 1
    bool_0 = True
    str_0 = module_0.uuid(bool_0)
    int_3 = -1
    generator_2 = module_0.roman_range(int_2, int_1, int_3)
    var_2 = list(generator_2)

def test_case_2():
    int_0 = 320
    str_0 = module_0.random_string(int_0)

def test_case_3():
    int_0 = 5
    generator_0 = module_0.roman_range(int_0)
    var_0 = list(generator_0)
    int_1 = 7
    generator_1 = module_0.roman_range(int_1)
    var_1 = list(generator_1)
    int_2 = 1
    int_3 = -1
    generator_2 = module_0.roman_range(int_2, int_1, int_3)
    var_2 = list(generator_2)